'use strict';

/**
 * Conduit Hub — VectraArch Automation, Social & Site Manager
 * Port: 3100 (internal, nginx proxies /conduit)
 * DB:   bookforge (forge_master) — same DB as VectraArchForge
 */

require('dotenv').config({ path: '/var/www/vectraarch.live/forge/.env' });
const pm2 = require('pm2');

const express  = require('express');
const session  = require('express-session');
const https    = require('https');
const fs       = require('fs');
const path     = require('path');
const { Pool } = require('pg');
const { verify, generateSecret, generateURI } = require('otplib');
const qrcode   = require('qrcode');

const app  = express();
const PORT = 3100;
const HOST = '127.0.0.1';
const BASE = '/conduit';

const TELEGRAM_TOKEN   = process.env.TELEGRAM_TOKEN   || '8767176406:AAEMhPAuQw5dFPEMcLEru1ZkqFT5ijk8YCk';
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID || '8783471876';
const PRESS_URL        = 'https://vectraarch.live/press';
const FORGE_URL        = 'https://vectraarch.live/forge';
const FOUNDATION_URL   = 'https://vectraarch.live/foundation/';
const WWW_ROOT         = '/var/www/vectraarch.live';

// ── DATABASE ──────────────────────────────────────────────────────────────────
// Connects to bookforge — same DB as VectraArchForge (shared users/books tables)
const pool = new Pool({
  user:     process.env.DB_USER,
  host:     process.env.DB_HOST     || 'localhost',
  database: process.env.DB_NAME,
  password: process.env.DB_PASSWORD,
  port:     parseInt(process.env.DB_PORT || '5432'),
});

// Read-only connection to VectraArchLegacy — same credentials, different DB
const legacyPool = new Pool({
  user:     process.env.DB_USER,
  host:     process.env.DB_HOST     || 'localhost',
  database: 'VectraArchLegacy',
  password: process.env.DB_PASSWORD,
  port:     parseInt(process.env.DB_PORT || '5432'),
});

// ── MIDDLEWARE ────────────────────────────────────────────────────────────────
app.set('trust proxy', 1);
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(session({
  secret:            process.env.SESSION_SECRET,
  resave:            false,
  saveUninitialized: false,
  cookie:            { secure: true, sameSite: 'lax', maxAge: 86400000 },
}));

// ── AUTH GUARD ────────────────────────────────────────────────────────────────
function isAuth(req, res, next) {
  if (!req.session.conduitUser) return res.redirect(FOUNDATION_URL);
  if (req.session.needs2FA)     return res.redirect(BASE + '/auth/2fa');
  next();
}

// ── DB SETUP ──────────────────────────────────────────────────────────────────
async function setupDB() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS conduit_log (
      id      SERIAL PRIMARY KEY,
      event   TEXT NOT NULL,
      payload TEXT,
      status  TEXT NOT NULL DEFAULT 'ok',
      created TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  console.log('[conduit] DB ready');
}

// ── KNOWN SITES ───────────────────────────────────────────────────────────────
const KNOWN_SITES = [
  { subdomain: '',          path: '/',            label: 'Home',         num: '—',     type: 'static',    purpose: 'Central hub · personal brand · studio map' },
  { subdomain: 'fabric',    path: '/fabric/',     label: 'Fabric',       num: '01/08', type: 'static',    purpose: 'Technical infrastructure portfolio' },
  { subdomain: 'conduit',   path: '/conduit/',    label: 'Conduit',      num: '02/08', type: 'node',      purpose: 'Automation & social hub · VectraArchConduit' },
  { subdomain: 'forge',     path: '/forge/',      label: 'Book Forge',   num: '03/08', type: 'node',      purpose: 'Writing management app · VectraArchForge' },
  { subdomain: 'keystone',  path: '/keystone/',   label: 'Keystone',     num: '04/08', type: 'static',    purpose: 'Constellation architecture documentation' },
  { subdomain: 'kinetic',   path: '/kinetic/',    label: 'Kinetic',      num: '05/08', type: 'static',    purpose: 'Visual portfolio · sculpture · gaming' },
  { subdomain: 'volition',  path: '/volition/',   label: 'Volition',     num: '06/08', type: 'static',    purpose: "Builder's log · process journal" },
  { subdomain: 'foundation',path: '/foundation/', label: 'Foundation',   num: '07/08', type: 'static',    purpose: 'Central auth hub · yellow warning zone' },
  { subdomain: 'press',     path: '/press/',      label: 'Press',        num: '08/08', type: 'generated', purpose: 'Auto-generated by VectraArchForge on publish' },
  { subdomain: 'bo7',       path: '/bo7/',        label: 'Bo7',          num: '—',     type: 'static',    purpose: 'CoD coaching platform · ZenithB_Actual' },
  { subdomain: 'legacy',    path: '/legacy/',     label: 'Legacy',       num: '—',     type: 'node',      purpose: 'Lifestyle app · VectraArchLegacy' },
  { subdomain: 'api',       path: '/api/',        label: 'Identity API', num: '—',     type: 'node',      purpose: 'VectraArch Identity Bridge · VectraArchIdentity · :3200' },
];

// ── API REGISTRY ──────────────────────────────────────────────────────────────
const API_REGISTRY = [
  { app: 'VectraArchForge',    method: 'POST',   path: '/forge/auth/manual',           desc: 'Manual login' },
  { app: 'VectraArchForge',    method: 'GET',    path: '/forge/auth/google',           desc: 'Google OAuth' },
  { app: 'VectraArchForge',    method: 'GET',    path: '/forge/auth/2fa',              desc: '2FA verify page' },
  { app: 'VectraArchForge',    method: 'POST',   path: '/forge/auth/2fa',              desc: '2FA submit' },
  { app: 'VectraArchForge',    method: 'GET',    path: '/forge/auth/2fa/setup',        desc: '2FA setup page' },
  { app: 'VectraArchForge',    method: 'POST',   path: '/forge/auth/2fa/setup',        desc: '2FA activate' },
  { app: 'VectraArchForge',    method: 'GET',    path: '/forge/logout',                desc: 'Logout' },
  { app: 'VectraArchForge',    method: 'POST',   path: '/forge/create-book',           desc: 'Create book' },
  { app: 'VectraArchForge',    method: 'GET',    path: '/forge/book/:id',              desc: 'Open book' },
  { app: 'VectraArchForge',    method: 'POST',   path: '/forge/book/:id/publish',      desc: 'Publish to Press' },
  { app: 'VectraArchForge',    method: 'POST',   path: '/forge/book/:id/unpublish',    desc: 'Unpublish from Press' },
  { app: 'VectraArchForge',    method: 'POST',   path: '/forge/book/:id/add',          desc: 'Add entry to book' },
  { app: 'VectraArchForge',    method: 'POST',   path: '/forge/book/delete/:id',       desc: 'Delete book' },
  { app: 'VectraArchForge',    method: 'GET',    path: '/forge/book/:id/export/:fmt',  desc: 'Export (docx/pdf/epub/md/txt)' },
  { app: 'VectraArchConduit',  method: 'POST',   path: '/conduit/login',               desc: 'Login' },
  { app: 'VectraArchConduit',  method: 'GET',    path: '/conduit/logout',              desc: 'Logout' },
  { app: 'VectraArchConduit',  method: 'GET',    path: '/conduit/auth/2fa',            desc: '2FA verify' },
  { app: 'VectraArchConduit',  method: 'POST',   path: '/conduit/auth/2fa',            desc: '2FA submit' },
  { app: 'VectraArchConduit',  method: 'GET',    path: '/conduit/auth/2fa/setup',      desc: '2FA setup' },
  { app: 'VectraArchConduit',  method: 'POST',   path: '/conduit/auth/2fa/disable',    desc: '2FA disable' },
  { app: 'VectraArchConduit',  method: 'POST',   path: '/conduit/announce',            desc: 'Telegram announcement' },
  { app: 'VectraArchConduit',  method: 'GET',    path: '/conduit/sites',               desc: 'Observatory' },
  { app: 'VectraArchConduit',  method: 'GET',    path: '/conduit/users',               desc: 'User management' },
  { app: 'VectraArchConduit',  method: 'POST',   path: '/conduit/log/clear',           desc: 'Clear event log' },
  { app: 'VectraArchLegacy',   method: 'POST',   path: '/legacy/api/login',            desc: 'Authentication' },
  { app: 'VectraArchLegacy',   method: 'POST',   path: '/legacy/api/verify-2fa',       desc: '2FA verification' },
  { app: 'VectraArchLegacy',   method: 'POST',   path: '/legacy/api/logout',           desc: 'Logout' },
  { app: 'VectraArchLegacy',   method: 'GET',    path: '/legacy/api/profile',          desc: 'Get profile' },
  { app: 'VectraArchLegacy',   method: 'POST',   path: '/legacy/api/transactions',     desc: 'Add transaction' },
  { app: 'VectraArchLegacy',   method: 'GET',    path: '/legacy/api/transactions',     desc: 'List transactions' },
  { app: 'VectraArchLegacy',   method: 'DELETE', path: '/legacy/api/transactions/:id', desc: 'Delete transaction' },
  { app: 'VectraArchLegacy',   method: 'POST',   path: '/legacy/api/import-statement', desc: 'Import bank statement' },
  { app: 'VectraArchIdentity', method: 'GET',    path: '/api/identity/health',         desc: 'Health check' },
  { app: 'VectraArchIdentity', method: 'POST',   path: '/api/identity/link',           desc: 'Link Legacy ↔ Forge identity' },
  { app: 'VectraArchIdentity', method: 'DELETE', path: '/api/identity/link',           desc: 'Unlink identity' },
  { app: 'VectraArchIdentity', method: 'GET',    path: '/api/identity/resolve',        desc: 'Resolve identity' },
  { app: 'VectraArchIdentity', method: 'GET',    path: '/api/identity/links',          desc: 'List all identity links' },
  { app: 'VectraArchIdentity', method: 'GET',    path: '/api/identity/audit',          desc: 'Identity audit log' },
];

// ── HELPERS ───────────────────────────────────────────────────────────────────
function esc(s) {
  return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

function postTelegram(text) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({ chat_id: TELEGRAM_CHAT_ID, text });
    const req = https.request(
      `https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage`,
      { method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) } },
      r => { let d=''; r.on('data',c=>d+=c); r.on('end',()=>{ try{resolve(JSON.parse(d));}catch{reject(new Error('Parse'));} }); }
    );
    req.on('error', reject); req.write(body); req.end();
  });
}

function siteIndexPath(sub) { return path.join(WWW_ROOT, sub||'', 'index.html'); }
function siteLastModified(sub) {
  try { return fs.statSync(siteIndexPath(sub)).mtime.toLocaleString('en-ZA'); } catch { return '—'; }
}

// ── PM2 ───────────────────────────────────────────────────────────────────────
function getPM2List() {
  return new Promise((resolve) => {
    pm2.connect(true, err => {
      if (err) return resolve([]);
      pm2.list((err, list) => {
        pm2.disconnect();
        if (err) return resolve([]);
        resolve(list.map(p => ({
          name:     p.name,
          status:   p.pm2_env.status,
          pid:      p.pid,
          uptime:   p.pm2_env.pm_uptime ? Math.floor((Date.now() - p.pm2_env.pm_uptime) / 1000) : 0,
          restarts: p.pm2_env.restart_time,
          memory:   p.monit ? Math.round(p.monit.memory / 1024 / 1024) : 0,
          cpu:      p.monit ? p.monit.cpu : 0,
        })));
      });
    });
  });
}

function formatUptime(s) {
  if (s < 60)    return s + 's';
  if (s < 3600)  return Math.floor(s/60) + 'm';
  if (s < 86400) return Math.floor(s/3600) + 'h ' + Math.floor((s%3600)/60) + 'm';
  return Math.floor(s/86400) + 'd ' + Math.floor((s%86400)/3600) + 'h';
}

// ── FONTS & CSS ───────────────────────────────────────────────────────────────
const FONTS = `<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Mono:wght@0,300;0,400;0,500&family=Barlow+Condensed:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>`;

const CSS = `
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0;}
:root{
  --bg:#0a0a08;--bg2:#111110;--bg3:#191917;
  --border:rgba(255,255,255,0.07);--border2:rgba(255,255,255,0.14);
  --text:#e8e4d8;--muted:rgba(232,228,216,0.5);--dim:rgba(232,228,216,0.22);
  --accent:#00ff41;--accent2:#00b32c;--red:#b84040;--warn:#d4a800;
  --auth-accent:#d4a017;--auth-accent2:#b8880f;--auth-accent3:#f0c040;
  --auth-glow-dim:rgba(212,160,23,0.06);
  --auth-border:rgba(212,160,23,0.35);--auth-border2:rgba(212,160,23,0.18);
}
html{scroll-behavior:smooth;}
body{background:var(--bg);color:var(--text);font-family:'DM Mono',monospace;font-size:13px;line-height:1.7;overflow-x:hidden;}
body::before{content:'';position:fixed;inset:0;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 512 512' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.75' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.035'/%3E%3C/svg%3E");opacity:0.4;pointer-events:none;z-index:0;}
.grid-bg{position:fixed;inset:0;background-image:linear-gradient(var(--border) 1px,transparent 1px),linear-gradient(90deg,var(--border) 1px,transparent 1px);background-size:80px 80px;pointer-events:none;z-index:0;}
.accent-lines{position:fixed;top:0;right:0;width:50%;height:100%;pointer-events:none;overflow:hidden;z-index:0;}
.accent-lines svg{width:100%;height:100%;}
nav{position:fixed;top:0;left:0;right:0;z-index:100;display:flex;align-items:center;justify-content:space-between;padding:0 32px;height:56px;border-bottom:1px solid var(--border);background:rgba(10,10,8,0.92);backdrop-filter:blur(12px);}
.nav-logo{font-family:'Barlow Condensed',sans-serif;font-weight:700;font-size:14px;letter-spacing:0.22em;text-transform:uppercase;color:var(--text);text-decoration:none;}
.nav-logo span{color:var(--accent);}
.nav-tabs{display:flex;align-items:center;}
.nav-tab{font-size:10px;letter-spacing:0.14em;text-transform:uppercase;color:var(--dim);text-decoration:none;padding:0 16px;height:56px;display:flex;align-items:center;border-bottom:2px solid transparent;transition:color 0.2s,border-color 0.2s;}
.nav-tab:hover{color:var(--muted);}
.nav-tab.active{color:var(--accent);border-bottom-color:var(--accent);}
.nav-right{display:flex;align-items:center;gap:16px;}
.nav-status{display:flex;align-items:center;gap:7px;font-size:10px;letter-spacing:0.1em;color:var(--dim);}
.nav-status::before{content:'';display:block;width:6px;height:6px;border-radius:50%;background:var(--accent);box-shadow:0 0 6px var(--accent);}
.nav-link{font-size:10px;letter-spacing:0.14em;text-transform:uppercase;color:var(--dim);text-decoration:none;transition:color 0.2s;}
.nav-link:hover{color:var(--muted);}
.wrap{position:relative;z-index:1;padding:80px 32px 60px;max-width:1200px;margin:0 auto;}
.page-title{font-family:'Bebas Neue',sans-serif;font-size:56px;line-height:0.9;color:var(--text);letter-spacing:0.02em;margin-bottom:6px;}
.page-sub{font-size:10px;letter-spacing:0.2em;text-transform:uppercase;color:var(--dim);margin-bottom:40px;}
.stat-row{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--border);margin-bottom:40px;}
.stat-cell{background:var(--bg2);padding:24px 20px;}
.stat-num{font-family:'Bebas Neue',sans-serif;font-size:2.4rem;line-height:1;color:var(--accent);margin-bottom:4px;}
.stat-num.r{color:var(--red);}
.stat-label{font-size:9px;letter-spacing:0.18em;text-transform:uppercase;color:var(--dim);}
.section{margin-bottom:40px;}
.section-hdr{display:flex;align-items:baseline;gap:16px;margin-bottom:20px;padding-bottom:12px;border-bottom:1px solid var(--border);}
.sh-num{font-size:10px;letter-spacing:0.2em;color:var(--dim);}
.sh-title{font-family:'Barlow Condensed',sans-serif;font-size:11px;font-weight:500;letter-spacing:0.28em;text-transform:uppercase;color:var(--muted);}
.sh-line{flex:1;height:1px;background:var(--border);}
table{width:100%;border-collapse:collapse;background:var(--bg2);}
th{font-size:9px;letter-spacing:0.18em;text-transform:uppercase;color:var(--dim);padding:12px 16px;text-align:left;border-bottom:1px solid var(--border2);}
td{padding:14px 16px;border-bottom:1px solid var(--border);color:var(--muted);font-size:12px;vertical-align:middle;}
tr:last-child td{border-bottom:none;}
tr:hover td{background:var(--bg3);}
.badge{display:inline-block;font-size:9px;letter-spacing:0.14em;text-transform:uppercase;padding:3px 10px;border:1px solid;}
.badge.ok{color:var(--accent);border-color:rgba(0,255,65,0.25);background:rgba(0,255,65,0.05);}
.badge.err{color:var(--red);border-color:rgba(184,64,64,0.25);background:rgba(184,64,64,0.05);}
.badge.info{color:var(--muted);border-color:var(--border2);}
.badge.warn{color:#d4a800;border-color:rgba(212,168,0,0.25);background:rgba(212,168,0,0.05);}
.btn{display:inline-flex;align-items:center;gap:8px;font-family:'DM Mono',monospace;font-size:10px;letter-spacing:0.16em;text-transform:uppercase;color:var(--text);background:none;border:1px solid var(--border2);padding:8px 16px;cursor:pointer;transition:border-color 0.2s,color 0.2s;text-decoration:none;}
.btn:hover{border-color:var(--accent);color:var(--accent);}
.btn.primary{background:var(--accent);color:#0a0a08;border-color:var(--accent);}
.btn.primary:hover{background:var(--accent2);border-color:var(--accent2);color:#fff;}
.btn.danger{border-color:rgba(184,64,64,0.4);color:var(--red);}
.btn.danger:hover{border-color:var(--red);background:rgba(184,64,64,0.06);}
.alert{padding:12px 16px;border:1px solid;font-size:11px;letter-spacing:0.08em;margin-bottom:20px;}
.alert.ok{color:var(--accent);border-color:rgba(0,255,65,0.25);background:rgba(0,255,65,0.05);}
.alert.err{color:var(--red);border-color:rgba(184,64,64,0.25);background:rgba(184,64,64,0.05);}
.form-wrap{background:var(--bg2);border:1px solid var(--border2);padding:32px;}
.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 32px;}
.form-group{display:flex;flex-direction:column;gap:6px;margin-bottom:24px;}
.form-group.full{grid-column:1/-1;}
.form-label{font-size:9px;letter-spacing:0.22em;text-transform:uppercase;color:var(--dim);}
.form-label .req{color:var(--red);}
.form-input,.form-select,.form-textarea{background:var(--bg);border:1px solid var(--border2);color:var(--text);font-family:'DM Mono',monospace;font-size:12px;letter-spacing:0.06em;padding:10px 14px;outline:none;transition:border-color 0.2s;width:100%;}
.form-input:focus,.form-select:focus,.form-textarea:focus{border-color:var(--accent);}
.form-input::placeholder,.form-textarea::placeholder{color:var(--dim);}
.form-textarea{resize:vertical;min-height:80px;}
.form-select{cursor:pointer;-webkit-appearance:none;}
.form-hint{font-size:9px;letter-spacing:0.1em;color:var(--dim);margin-top:4px;}
.form-section{margin-bottom:32px;padding-bottom:32px;border-bottom:1px solid var(--border);}
.form-section:last-of-type{border-bottom:none;}
.form-section-title{font-family:'Barlow Condensed',sans-serif;font-size:13px;font-weight:600;letter-spacing:0.2em;text-transform:uppercase;color:var(--muted);margin-bottom:20px;}
.form-actions{display:flex;gap:12px;padding-top:20px;border-top:1px solid var(--border);}
.narrative-block{background:var(--bg3);border:1px solid var(--border);padding:20px;margin-bottom:12px;}
.narrative-block-title{font-size:9px;letter-spacing:0.2em;text-transform:uppercase;color:var(--accent2);margin-bottom:14px;}
.code-block{background:var(--bg3);border:1px solid var(--border2);padding:20px 24px;font-family:'DM Mono',monospace;font-size:12px;color:var(--accent);letter-spacing:0.06em;line-height:2;white-space:pre;overflow-x:auto;}
/* ── AUTH PAGES (yellow warning zone) ── */
.auth-wrap{min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:40px;position:relative;z-index:1;}
.auth-card{width:100%;max-width:440px;border:1px solid var(--auth-border);background:var(--bg2);padding:48px 40px 40px;position:relative;}
.auth-card::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;background:var(--auth-accent);}
.auth-eyebrow{font-family:'Barlow Condensed',sans-serif;font-size:9px;letter-spacing:0.28em;text-transform:uppercase;color:var(--auth-accent);margin-bottom:16px;}
.auth-title{font-family:'Bebas Neue',sans-serif;font-size:56px;line-height:0.9;color:var(--text);margin-bottom:4px;}
.auth-sub{font-family:'Barlow Condensed',sans-serif;font-weight:300;font-size:12px;letter-spacing:0.1em;text-transform:uppercase;color:var(--muted);margin-bottom:32px;}
.auth-warning{display:flex;align-items:center;gap:10px;border:1px solid var(--auth-border2);background:var(--auth-glow-dim);padding:10px 14px;margin-bottom:28px;}
.auth-warning-dot{width:6px;height:6px;border-radius:50%;background:var(--auth-accent);box-shadow:0 0 6px var(--auth-accent);flex-shrink:0;animation:pulse-warn 2s ease-in-out infinite;}
@keyframes pulse-warn{0%,100%{opacity:1;box-shadow:0 0 6px var(--auth-accent);}50%{opacity:0.6;box-shadow:0 0 14px var(--auth-accent3);}}
.auth-warning-text{font-family:'DM Mono',monospace;font-size:9px;letter-spacing:0.16em;text-transform:uppercase;color:var(--auth-accent);}
.auth-field{display:flex;flex-direction:column;gap:6px;margin-bottom:20px;}
.auth-label{font-family:'DM Mono',monospace;font-size:9px;letter-spacing:0.22em;text-transform:uppercase;color:var(--dim);}
.auth-input{background:transparent;border:none;border-bottom:1px solid var(--border2);padding:10px 0;font-family:'DM Mono',monospace;font-size:13px;color:var(--text);outline:none;transition:border-color 0.2s;width:100%;}
.auth-input::placeholder{color:var(--dim);}
.auth-input:focus{border-bottom-color:var(--auth-accent);}
.auth-input-code{font-size:28px;letter-spacing:0.35em;text-align:center;}
.auth-submit{width:100%;background:var(--auth-accent);color:#0a0a08;border:none;font-family:'DM Mono',monospace;font-size:11px;letter-spacing:0.18em;text-transform:uppercase;padding:14px 20px;cursor:pointer;transition:background 0.2s;margin-top:8px;}
.auth-submit:hover{background:var(--auth-accent3);color:#0a0a08;}
.auth-error{font-family:'DM Mono',monospace;font-size:10px;letter-spacing:0.14em;color:var(--red);border:1px solid rgba(184,64,64,0.3);padding:10px 14px;margin-top:16px;}
.auth-back{display:block;text-align:center;margin-top:24px;font-family:'DM Mono',monospace;font-size:9px;letter-spacing:0.14em;color:var(--dim);text-decoration:none;transition:color 0.2s;}
.auth-back:hover{color:var(--auth-accent);}
.auth-qr-frame{text-align:center;margin-bottom:20px;background:#fff;padding:16px;display:inline-block;width:100%;box-sizing:border-box;}
.auth-qr-frame img{width:160px;height:160px;display:block;margin:0 auto;}
.auth-secret{font-family:'DM Mono',monospace;font-size:10px;letter-spacing:0.18em;color:var(--auth-accent);text-align:center;margin-bottom:24px;border:1px solid var(--auth-border2);padding:10px 14px;background:var(--auth-glow-dim);word-break:break-all;}
.auth-secret-label{display:block;font-size:8px;letter-spacing:0.2em;color:var(--dim);margin-bottom:6px;text-transform:uppercase;}
@media(max-width:768px){.stat-row{grid-template-columns:1fr 1fr;}.wrap{padding:72px 20px 40px;}.form-grid{grid-template-columns:1fr;}.auth-card{padding:36px 24px 32px;}.auth-wrap{padding:40px 20px;}}
`;

const AUTH_SVG = `<div class="accent-lines" aria-hidden="true">
  <svg viewBox="0 0 600 900" fill="none" preserveAspectRatio="xMaxYMid slice">
    <line x1="580" y1="0" x2="20" y2="900" stroke="rgba(212,160,23,0.07)" stroke-width="1"/>
    <line x1="540" y1="0" x2="0" y2="760" stroke="rgba(212,160,23,0.05)" stroke-width="0.5"/>
    <circle cx="540" cy="180" r="60"  stroke="rgba(212,160,23,0.06)"  stroke-width="1"   fill="none"/>
    <circle cx="540" cy="180" r="90"  stroke="rgba(212,160,23,0.04)"  stroke-width="0.5" fill="none"/>
    <circle cx="540" cy="180" r="130" stroke="rgba(212,160,23,0.025)" stroke-width="0.5" fill="none"/>
  </svg>
</div>`;

// ── LAYOUT (dashboard — green accent) ─────────────────────────────────────────
function layout(title, activeTab, body) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>${esc(title)} · Conduit</title>${FONTS}<style>${CSS}</style></head><body>
<div class="grid-bg"></div>
<nav>
  <a href="${BASE}/" class="nav-logo">Vectra<span>&nbsp;</span>Arch · Conduit</a>
  <div class="nav-tabs">
    <a href="${BASE}/"      class="nav-tab ${activeTab==='dashboard'?'active':''}">Dashboard</a>
    <a href="${BASE}/sites" class="nav-tab ${activeTab==='sites'?'active':''}">Observatory</a>
    <a href="${BASE}/users" class="nav-tab ${activeTab==='users'?'active':''}">Users</a>
  </div>
  <div class="nav-right">
    <div class="nav-status">HUB · LIVE</div>
    <a href="${FORGE_URL}" class="nav-link" target="_blank">Forge ↗</a>
    <a href="${BASE}/logout" class="nav-link">Logout</a>
  </div>
</nav>
<div class="wrap">${body}</div>
</body></html>`;
}

// ── AUTH PAGE FUNCTIONS (yellow warning zone) ─────────────────────────────────
function loginPage(err) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>Conduit · Access</title>${FONTS}<style>${CSS}</style></head><body>
<div class="grid-bg"></div>${AUTH_SVG}
<div class="auth-wrap">
  <div class="auth-card">
    <div class="auth-eyebrow">§ Vectra Arch · Conduit Hub</div>
    <div class="auth-title">Access</div>
    <div class="auth-sub">Automation &amp; Social Hub · Authorised Entry Only</div>
    <div class="auth-warning"><div class="auth-warning-dot"></div><span class="auth-warning-text">Restricted · Authorised Personnel Only</span></div>
    <form method="POST" action="${BASE}/login">
      <div class="auth-field"><label class="auth-label">Username</label><input class="auth-input" name="cid" type="text" placeholder="username" autocomplete="username" required autofocus/></div>
      <div class="auth-field"><label class="auth-label">Key</label><input class="auth-input" name="ak" type="password" placeholder="········" autocomplete="current-password" required/></div>
      <button class="auth-submit" type="submit">Authenticate ↗</button>
      ${err?`<div class="auth-error">⚠ ${esc(err)}</div>`:''}
    </form>
    <a href="${FOUNDATION_URL}" class="auth-back">← Back to Foundation</a>
  </div>
</div></body></html>`;
}

function twoFAVerifyPage(err) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>2FA · Conduit</title>${FONTS}<style>${CSS}</style></head><body>
<div class="grid-bg"></div>${AUTH_SVG}
<div class="auth-wrap">
  <div class="auth-card">
    <div class="auth-eyebrow">§ Vectra Arch · Conduit · 2FA</div>
    <div class="auth-title">Verify</div>
    <div class="auth-sub">vectraarch.live/conduit · Identity Confirmation</div>
    <div class="auth-warning"><div class="auth-warning-dot"></div><span class="auth-warning-text">2FA Required · Authorised Access Only</span></div>
    ${err?`<div class="auth-error">⚠ ${esc(err)}</div>`:''}
    <form method="POST" action="${BASE}/auth/2fa">
      <div class="auth-field"><label class="auth-label">Authentication Code</label><input class="auth-input auth-input-code" name="token" type="text" placeholder="000000" maxlength="6" autocomplete="one-time-code" required autofocus/></div>
      <button class="auth-submit" type="submit">Verify ↗</button>
    </form>
    <a href="${FOUNDATION_URL}" class="auth-back">← Back to Foundation</a>
  </div>
</div></body></html>`;
}

async function twoFASetupPage(qr, secret, err) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>Setup 2FA · Conduit</title>${FONTS}<style>${CSS}</style></head><body>
<div class="grid-bg"></div>${AUTH_SVG}
<div class="auth-wrap">
  <div class="auth-card">
    <div class="auth-eyebrow">§ Vectra Arch · Conduit · Security</div>
    <div class="auth-title">Enable 2FA</div>
    <div class="auth-sub">vectraarch.live/conduit · Link Your Authenticator</div>
    <div class="auth-warning"><div class="auth-warning-dot"></div><span class="auth-warning-text">Security Setup · Keep This Key Private</span></div>
    ${qr?`<div class="auth-qr-frame"><img src="${qr}" alt="QR Code"/></div>`:''}
    <div class="auth-secret"><span class="auth-secret-label">Manual key — enter in your authenticator app</span>${esc(secret||'')}</div>
    ${err?`<div class="auth-error">⚠ ${esc(err)}</div>`:''}
    <form method="POST" action="${BASE}/auth/2fa/setup">
      <div class="auth-field"><label class="auth-label">Confirm Code</label><input class="auth-input auth-input-code" name="token" type="text" placeholder="000000" maxlength="6" autocomplete="one-time-code" required autofocus/></div>
      <button class="auth-submit" type="submit">Activate 2FA ↗</button>
    </form>
    <a href="${BASE}/" class="auth-back">← Cancel</a>
  </div>
</div></body></html>`;
}

// ── AUTH ROUTES ───────────────────────────────────────────────────────────────
app.get(BASE + '/login', (req, res) => {
  if (req.session.conduitUser) return res.redirect(BASE + '/');
  res.send(loginPage());
});

app.post(BASE + '/login', async (req, res) => {
  const { cid, ak } = req.body;
  try {
    const r = await pool.query(
      `SELECT * FROM users WHERE LOWER(name)=LOWER($1) AND password=$2 AND role='admin'`,
      [cid||'', ak||'']
    );
    if (r.rows[0]?.status === 'enabled') {
      req.session.conduitUser = { id: r.rows[0].id, name: r.rows[0].name };
      await pool.query('UPDATE users SET logins=logins+1, last_login=$1 WHERE id=$2',
        [new Date().toLocaleString('en-ZA'), r.rows[0].id]);
      if (r.rows[0].twofa_secret) {
        req.session.needs2FA = true;
        return res.redirect(BASE + '/auth/2fa');
      }
      return res.redirect(BASE + '/');
    }
    res.send(loginPage('Invalid credentials'));
  } catch (e) {
    console.error('[conduit] Login error:', e);
    res.send(loginPage('System error — try again'));
  }
});

app.get(BASE + '/logout', (req, res) => {
  req.session.destroy();
  res.redirect(FOUNDATION_URL);
});

// ── 2FA ROUTES ────────────────────────────────────────────────────────────────
app.get(BASE + '/auth/2fa', (req, res) => {
  if (!req.session.conduitUser) return res.redirect(FOUNDATION_URL);
  if (!req.session.needs2FA)    return res.redirect(BASE + '/');
  res.send(twoFAVerifyPage());
});

app.post(BASE + '/auth/2fa', async (req, res) => {
  if (!req.session.conduitUser) return res.redirect(FOUNDATION_URL);
  const u = await pool.query('SELECT twofa_secret FROM users WHERE id=$1', [req.session.conduitUser.id]);
  const secret = u.rows[0]?.twofa_secret;
  if (!secret) { delete req.session.needs2FA; return res.redirect(BASE + '/'); }
  try {
    if (verify({ token: req.body.token||'', secret })) {
      delete req.session.needs2FA;
      return res.redirect(BASE + '/');
    }
    res.send(twoFAVerifyPage('Invalid code — try again'));
  } catch { delete req.session.needs2FA; res.redirect(BASE + '/'); }
});

app.get(BASE + '/auth/2fa/setup', isAuth, async (req, res) => {
  const u = await pool.query('SELECT twofa_secret FROM users WHERE id=$1', [req.session.conduitUser.id]);
  if (u.rows[0]?.twofa_secret) return res.redirect(BASE + '/');
  const secret = generateSecret();
  req.session.tempSecret = secret;
  const qr = await qrcode.toDataURL(generateURI({ secret, label: req.session.conduitUser.id, issuer: 'ConduitHub' }));
  res.send(await twoFASetupPage(qr, secret));
});

app.post(BASE + '/auth/2fa/setup', isAuth, async (req, res) => {
  if (!req.session.tempSecret) return res.redirect(BASE + '/');
  if (verify({ token: req.body.token||'', secret: req.session.tempSecret })) {
    await pool.query('UPDATE users SET twofa_secret=$1 WHERE id=$2', [req.session.tempSecret, req.session.conduitUser.id]);
    delete req.session.tempSecret;
    req.session.flash = { type:'ok', msg:'✓ Two-factor authentication enabled' };
    return res.redirect(BASE + '/');
  }
  const qr = await qrcode.toDataURL(generateURI({ secret: req.session.tempSecret, label: req.session.conduitUser.id, issuer: 'ConduitHub' }));
  res.send(await twoFASetupPage(qr, req.session.tempSecret, 'Invalid code — try again'));
});

app.post(BASE + '/auth/2fa/disable', isAuth, async (req, res) => {
  await pool.query('UPDATE users SET twofa_secret=NULL WHERE id=$1', [req.session.conduitUser.id]);
  req.session.flash = { type:'ok', msg:'✓ Two-factor authentication disabled' };
  res.redirect(BASE + '/');
});

// ── DASHBOARD ─────────────────────────────────────────────────────────────────
app.get(BASE + '/', isAuth, async (req, res) => {
  const flash = req.session.flash; delete req.session.flash;

  // Check 2FA status for current user
  const userRow  = await pool.query('SELECT twofa_secret FROM users WHERE id=$1', [req.session.conduitUser.id]);
  const has2FA   = !!userRow.rows[0]?.twofa_secret;

  // All published books with author name and last announcement time
  const books = await pool.query(`
    SELECT b.id, b.title, u.name AS author_name,
           (SELECT created FROM conduit_log
            WHERE payload LIKE '%' || b.id || '%' AND event='announcement'
            ORDER BY created DESC LIMIT 1) AS last_announced
    FROM books b
    JOIN users u ON b.owner_id = u.id
    WHERE b.published = true
    ORDER BY u.name ASC, b.title ASC
  `);

  // Last 20 log events
  const logs = await pool.query(
    'SELECT id,event,payload,status,created FROM conduit_log ORDER BY created DESC LIMIT 20'
  );

  const bookRows = books.rows.map(b => `
    <tr>
      <td style="color:var(--text)">${esc(b.title)}</td>
      <td>${esc(b.author_name)}</td>
      <td><span class="badge ok">Published</span></td>
      <td style="font-size:10px;color:var(--dim)">${b.last_announced ? new Date(b.last_announced).toLocaleString('en-ZA') : '—'}</td>
      <td>
        <form method="POST" action="${BASE}/announce" style="display:inline;">
          <input type="hidden" name="book_id"     value="${esc(b.id)}"/>
          <input type="hidden" name="book_title"  value="${esc(b.title)}"/>
          <input type="hidden" name="author_name" value="${esc(b.author_name)}"/>
          <button class="btn" type="submit">Post ↗</button>
        </form>
      </td>
    </tr>`).join('');

  const logRows = logs.rows.map(l => `
    <tr>
      <td style="font-size:10px;">${new Date(l.created).toLocaleString('en-ZA')}</td>
      <td><span class="badge ${l.status==='ok'?'ok':'err'}">${esc(l.event)}</span></td>
      <td style="font-size:11px;max-width:400px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">${esc(l.payload||'')}</td>
      <td><span class="badge ${l.status==='ok'?'ok':'err'}">${esc(l.status)}</span></td>
    </tr>`).join('');

  const body = `
    <div class="page-title">Conduit</div>
    <div class="page-sub">§ Automation &amp; Social Hub · bookforge DB · VectraArch</div>
    ${flash?`<div class="alert ${flash.type}">${esc(flash.msg)}</div>`:''}

    <div class="stat-row">
      <div class="stat-cell"><div class="stat-num">${books.rows.length}</div><div class="stat-label">Published Volumes</div></div>
      <div class="stat-cell"><div class="stat-num">${logs.rows.filter(l=>l.event==='announcement').length}</div><div class="stat-label">Announcements Sent</div></div>
      <div class="stat-cell"><div class="stat-num">${logs.rows.filter(l=>l.status==='ok').length}</div><div class="stat-label">Successful Events</div></div>
      <div class="stat-cell"><div class="stat-num r">${logs.rows.filter(l=>l.status==='err').length}</div><div class="stat-label">Failed Events</div></div>
    </div>

    <div class="section">
      <div class="section-hdr"><span class="sh-num">00</span><span class="sh-title">Your Account · Two-Factor Authentication</span><div class="sh-line"></div></div>
      <div style="background:var(--bg2);border:1px solid var(--border2);padding:24px 28px;display:flex;align-items:center;justify-content:space-between;gap:20px;">
        <div>
          <div style="font-family:'Barlow Condensed',sans-serif;font-weight:600;font-size:15px;letter-spacing:0.06em;text-transform:uppercase;color:var(--text);margin-bottom:6px;">
            2FA: <span style="color:${has2FA?'var(--accent)':'var(--red)'};">${has2FA?'Enabled':'Disabled'}</span>
          </div>
          <div style="font-size:11px;color:var(--dim);letter-spacing:0.08em;">
            ${has2FA?'Your account is protected with two-factor authentication.':'Enable 2FA for an additional layer of security.'}
          </div>
        </div>
        <div>${has2FA
          ? `<form method="POST" action="${BASE}/auth/2fa/disable"><button class="btn danger" type="submit" onclick="return confirm('Disable 2FA?')">Disable 2FA</button></form>`
          : `<a href="${BASE}/auth/2fa/setup" class="btn primary">Enable 2FA ↗</a>`}
        </div>
      </div>
    </div>

    <div class="section">
      <div class="section-hdr"><span class="sh-num">01</span><span class="sh-title">Published Volumes · Post Announcement</span><div class="sh-line"></div></div>
      ${books.rows.length === 0
        ? '<div style="padding:32px;background:var(--bg2);color:var(--dim);text-align:center;letter-spacing:0.1em;">No published volumes in bookforge</div>'
        : `<table><thead><tr><th>Title</th><th>Author</th><th>Status</th><th>Last Announced</th><th>Action</th></tr></thead><tbody>${bookRows}</tbody></table>`}
    </div>

    <div class="section">
      <div class="section-hdr">
        <span class="sh-num">02</span><span class="sh-title">Trigger Log · Last 20 Events</span><div class="sh-line"></div>
        <form method="POST" action="${BASE}/log/clear" style="margin-left:auto;">
          <button class="btn danger" type="submit" onclick="return confirm('Clear all logs?')">Clear Log</button>
        </form>
      </div>
      ${logs.rows.length === 0
        ? '<div style="padding:32px;background:var(--bg2);color:var(--dim);text-align:center;letter-spacing:0.1em;">No events logged yet</div>'
        : `<table><thead><tr><th>Time</th><th>Event</th><th>Payload</th><th>Status</th></tr></thead><tbody>${logRows}</tbody></table>`}
    </div>`;

  res.send(layout('Dashboard', 'dashboard', body));
});

// ── ANNOUNCE ──────────────────────────────────────────────────────────────────
app.post(BASE + '/announce', isAuth, async (req, res) => {
  const { book_id, book_title, author_name } = req.body;
  const text = `📖 New Publication · Vectra Arch Press\n\n"${book_title}"\nby ${author_name}\n\nRead it now → ${PRESS_URL}`;
  try {
    const tgRes = await postTelegram(text);
    await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)',
      ['announcement', `book_id:${book_id} title:${book_title} author:${author_name}`, tgRes.ok?'ok':'err']);
    req.session.flash = { type:'ok', msg:`✓ Announcement posted for "${book_title}"` };
  } catch (e) {
    await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)',
      ['announcement', `book_id:${book_id} ERROR:${e.message}`, 'err']);
    req.session.flash = { type:'err', msg:`✗ Failed: ${e.message}` };
  }
  res.redirect(BASE + '/');
});

app.post(BASE + '/log/clear', isAuth, async (req, res) => {
  await pool.query('DELETE FROM conduit_log');
  req.session.flash = { type:'ok', msg:'✓ Log cleared' };
  res.redirect(BASE + '/');
});

// ── OBSERVATORY ───────────────────────────────────────────────────────────────
app.get(BASE + '/sites', isAuth, async (req, res) => {
  const flash    = req.session.flash; delete req.session.flash;
  const pm2List  = await getPM2List();

  const pm2Rows = pm2List.map(p => `
    <tr>
      <td style="color:var(--text);font-weight:500">${esc(p.name)}</td>
      <td><span class="badge ${p.status==='online'?'ok':'err'}">${esc(p.status)}</span></td>
      <td style="font-size:10px;color:var(--dim)">${p.pid||'—'}</td>
      <td style="font-size:10px;color:var(--dim)">${p.status==='online'?formatUptime(p.uptime):'—'}</td>
      <td style="font-size:10px;color:var(--dim)">${p.restarts}</td>
      <td style="font-size:10px;color:${p.memory>200?'var(--red)':'var(--muted)'}">${p.memory} mb</td>
      <td style="font-size:10px;color:var(--dim)">${p.cpu}%</td>
    </tr>`).join('');

  const siteRows = KNOWN_SITES.map(s => {
    const lm  = siteLastModified(s.subdomain);
    const url = `https://vectraarch.live${s.path||'/'+s.subdomain+'/'}`;
    const typeBadge = s.type==='static'    ? `<span class="badge ok">Static</span>`
                    : s.type==='node'      ? `<span class="badge info">Node.js</span>`
                    : s.type==='generated' ? `<span class="badge warn">Auto-gen</span>`
                    : `<span class="badge info">${esc(s.type)}</span>`;
    return `<tr>
      <td><a href="${esc(url)}" target="_blank" style="color:var(--accent);text-decoration:none;">vectraarch.live${esc(s.path||'/'+s.subdomain+'/')} ↗</a></td>
      <td style="color:var(--text)">${esc(s.label)}</td>
      <td>${typeBadge}</td>
      <td style="color:var(--dim);font-size:11px;">${esc(s.purpose)}</td>
      <td style="font-size:10px;color:var(--dim)">${esc(lm)}</td>
    </tr>`;
  }).join('');

  // Group API registry by app
  const appGroups = {};
  API_REGISTRY.forEach(e => { if (!appGroups[e.app]) appGroups[e.app]=[]; appGroups[e.app].push(e); });
  const apiSections = Object.entries(appGroups).map(([appName, endpoints]) => `
    <div style="margin-bottom:28px;">
      <div style="font-size:10px;letter-spacing:0.18em;text-transform:uppercase;color:var(--accent2);margin-bottom:10px;">${esc(appName)}</div>
      <table><thead><tr><th>Method</th><th>Path</th><th>Description</th></tr></thead><tbody>
        ${endpoints.map(e=>`<tr>
          <td><span class="badge ${e.method==='GET'?'ok':e.method==='DELETE'?'err':'info'}" style="font-size:8px;">${esc(e.method)}</span></td>
          <td style="font-family:'DM Mono',monospace;font-size:11px;color:var(--text)">${esc(e.path)}</td>
          <td style="font-size:11px;color:var(--dim)">${esc(e.desc)}</td>
        </tr>`).join('')}
      </tbody></table>
    </div>`).join('');

  const body = `
    <div class="page-title">Observatory</div>
    <div class="page-sub">§ Constellation Map · ${KNOWN_SITES.length} Sites · ${API_REGISTRY.length} Endpoints</div>
    ${flash?`<div class="alert ${flash.type}">${esc(flash.msg)}</div>`:''}

    <div class="section">
      <div class="section-hdr"><span class="sh-num">01</span><span class="sh-title">PM2 Processes · Live Status</span><div class="sh-line"></div></div>
      ${pm2List.length===0
        ? '<div style="padding:24px;background:var(--bg2);color:var(--dim);text-align:center;letter-spacing:0.1em;font-size:10px;">PM2 data unavailable</div>'
        : `<table><thead><tr><th>Name</th><th>Status</th><th>PID</th><th>Uptime</th><th>Restarts</th><th>Memory</th><th>CPU</th></tr></thead><tbody>${pm2Rows}</tbody></table>`}
    </div>

    <div class="section">
      <div class="section-hdr"><span class="sh-num">02</span><span class="sh-title">Constellation · ${KNOWN_SITES.length} Sites</span><div class="sh-line"></div></div>
      <table><thead><tr><th>Path</th><th>Label</th><th>Type</th><th>Purpose</th><th>Last Modified</th></tr></thead><tbody>${siteRows}</tbody></table>
    </div>

    <div class="section">
      <div class="section-hdr"><span class="sh-num">03</span><span class="sh-title">API Registry · ${API_REGISTRY.length} Endpoints</span><div class="sh-line"></div></div>
      ${apiSections}
    </div>`;

  res.send(layout('Observatory', 'sites', body));
});

// ── USERS ─────────────────────────────────────────────────────────────────────
app.get(BASE + '/users', isAuth, async (req, res) => {
  const flash = req.session.flash; delete req.session.flash;

  // ── Forge users ──
  const result = await pool.query(`
    SELECT id, name, type, role, status, logins, last_login,
           (twofa_secret IS NOT NULL) AS twofa_enabled,
           CASE WHEN type='Manual' THEN COALESCE(email,'[No email set]') ELSE email END AS display_email
    FROM users ORDER BY last_login DESC NULLS LAST
  `);
  const users = result.rows;

  // ── Legacy users + access list ──
  let legacyUsers = [], accessList = [];
  try {
    const lr = await legacyPool.query(`
      SELECT username, first_name, last_name, display_name, email, is_admin,
             activity_status, last_active, (twofa_secret IS NOT NULL) AS twofa_enabled
      FROM vectraarchlegacy_users ORDER BY last_active DESC NULLS LAST
    `);
    legacyUsers = lr.rows;
    const ar = await legacyPool.query('SELECT viewer, target FROM vectraarchlegacy_access ORDER BY viewer');
    accessList = ar.rows;
  } catch(e) { console.error('[conduit] Legacy DB error:', e.message); }

  const usernames = legacyUsers.map(u => u.username);

  // ── Forge rows ──
  const forgeRows = users.map(u => `
    <tr>
      <td>
        <div style="color:var(--text);font-size:12px;">${esc(u.name)}</div>
        <div style="color:var(--dim);font-size:10px;">${esc(u.display_email)}</div>
        <div style="color:var(--dim);font-size:9px;letter-spacing:0.1em;margin-top:2px;">${esc(u.id)}</div>
      </td>
      <td><span class="badge ${u.type==='Google'?'ok':'info'}">${esc(u.type)}</span></td>
      <td><span class="badge ${u.role==='admin'?'warn':'info'}">${esc(u.role)}</span></td>
      <td><span class="badge ${u.status==='enabled'?'ok':'err'}">${esc(u.status)}</span></td>
      <td style="font-size:10px;color:var(--dim)">${u.logins||0}</td>
      <td style="font-size:10px;color:var(--dim)">${u.last_login||'—'}</td>
      <td><span class="badge ${u.twofa_enabled?'ok':'info'}">${u.twofa_enabled?'On':'Off'}</span></td>
      <td style="white-space:nowrap;">
        <div style="display:flex;gap:6px;flex-wrap:wrap;">
          <button class="btn" onclick="toggleEdit('forge_${esc(u.id)}')" type="button">Edit</button>
          ${u.twofa_enabled?`<form method="POST" action="${BASE}/users/reset-2fa/${encodeURIComponent(u.id)}" style="display:inline;">
            <button class="btn" type="submit" onclick="return confirm('Reset 2FA?')">2FA ✕</button></form>`:''}
          <form method="POST" action="${BASE}/users/toggle/${encodeURIComponent(u.id)}" style="display:inline;">
            <input type="hidden" name="status" value="${u.status==='enabled'?'disabled':'enabled'}"/>
            <button class="btn ${u.status==='enabled'?'danger':''}" type="submit">${u.status==='enabled'?'Disable':'Enable'}</button>
          </form>
          ${u.id!==req.session.conduitUser.id?`<form method="POST" action="${BASE}/users/delete/${encodeURIComponent(u.id)}" style="display:inline;">
            <button class="btn danger" type="submit" onclick="return confirm('Delete ${esc(u.name)}?')">Delete</button></form>`
          :'<span style="font-size:9px;color:var(--dim);padding:8px 0;">(you)</span>'}
        </div>
        <div id="edit-forge_${esc(u.id)}" style="display:none;margin-top:12px;background:var(--bg3);border:1px solid var(--border2);padding:16px;">
          <form method="POST" action="${BASE}/users/edit/${encodeURIComponent(u.id)}">
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:10px;">
              <div><div class="form-label" style="margin-bottom:4px;">Name</div>
                <input class="form-input" name="name" value="${esc(u.name)}" required/></div>
              <div><div class="form-label" style="margin-bottom:4px;">Role</div>
                <select class="form-select" name="role">
                  <option value="user" ${u.role==='user'?'selected':''}>User</option>
                  <option value="admin" ${u.role==='admin'?'selected':''}>Admin</option>
                </select></div>
              ${u.type==='Manual'?`
              <div><div class="form-label" style="margin-bottom:4px;">Email</div>
                <input class="form-input" name="email" type="email" value="${esc(u.display_email==='[No email set]'?'':u.display_email)}"/></div>
              <div><div class="form-label" style="margin-bottom:4px;">New Password</div>
                <input class="form-input" name="password" type="password" placeholder="leave blank to keep"/></div>`
              :'<div></div><div></div>'}
            </div>
            <div style="display:flex;gap:8px;">
              <button class="btn primary" type="submit">Save</button>
              <button class="btn" type="button" onclick="toggleEdit('forge_${esc(u.id)}')">Cancel</button>
            </div>
          </form>
        </div>
      </td>
    </tr>`).join('');

  // ── Legacy rows ──
  const legacyRows = legacyUsers.map(u => `
    <tr>
      <td>
        <div style="color:var(--text);font-size:12px;font-weight:600;">${esc(u.username)}</div>
        ${u.first_name||u.last_name?`<div style="color:var(--dim);font-size:10px;">${esc([u.first_name,u.last_name].filter(Boolean).join(' '))}</div>`:''}
        ${u.display_name&&u.display_name!==u.username?`<div style="color:var(--dim);font-size:9px;letter-spacing:0.05em;">${esc(u.display_name)}</div>`:''}
      </td>
      <td style="font-size:11px;color:var(--dim)">${esc(u.email||'—')}</td>
      <td><span class="badge ${u.is_admin?'warn':'info'}">${u.is_admin?'Admin':'User'}</span></td>
      <td><span class="badge ${u.activity_status?'ok':'info'}">${u.activity_status?'Active':'Inactive'}</span></td>
      <td>
        <div style="display:flex;align-items:center;gap:6px;">
          <span class="badge ${u.twofa_enabled?'ok':'info'}">${u.twofa_enabled?'ON':'OFF'}</span>
          ${u.twofa_enabled?`<form method="POST" action="${BASE}/users/legacy/toggle-2fa/${encodeURIComponent(u.username)}" style="display:inline;">
            <input type="hidden" name="action" value="disable"/>
            <button class="btn" style="padding:3px 8px;font-size:9px;" type="submit" onclick="return confirm('Disable 2FA for ${esc(u.username)}?')">Disable</button>
          </form>`:'<span style="font-size:9px;color:var(--dim);">—</span>'}
        </div>
      </td>
      <td style="font-size:10px;color:var(--dim)">${u.last_active?new Date(u.last_active).toLocaleString('en-ZA'):'—'}</td>
      <td style="white-space:nowrap;">
        <div style="display:flex;gap:6px;flex-wrap:wrap;">
          <button class="btn" onclick="toggleEdit('leg_${esc(u.username)}')" type="button">Edit</button>
          <form method="POST" action="${BASE}/users/legacy/delete/${encodeURIComponent(u.username)}" style="display:inline;">
            <button class="btn danger" type="submit" onclick="return confirm('Permanently delete Legacy user ${esc(u.username)} and ALL their data?')">Delete</button>
          </form>
        </div>
        <div id="edit-leg_${esc(u.username)}" style="display:none;margin-top:12px;background:var(--bg3);border:1px solid var(--border2);padding:16px;">
          <form method="POST" action="${BASE}/users/legacy/edit/${encodeURIComponent(u.username)}">
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:10px;">
              <div><div class="form-label" style="margin-bottom:4px;">First Name</div>
                <input class="form-input" name="firstName" value="${esc(u.first_name||'')}" placeholder="First name"/></div>
              <div><div class="form-label" style="margin-bottom:4px;">Last Name</div>
                <input class="form-input" name="lastName" value="${esc(u.last_name||'')}" placeholder="Last name"/></div>
              <div><div class="form-label" style="margin-bottom:4px;">Email</div>
                <input class="form-input" name="email" type="email" value="${esc(u.email||'')}" placeholder="email@address.com"/></div>
              <div><div class="form-label" style="margin-bottom:4px;">New Password</div>
                <input class="form-input" name="password" type="password" placeholder="leave blank to keep"/></div>
              <div><div class="form-label" style="margin-bottom:4px;">Role</div>
                <select class="form-select" name="isAdmin">
                  <option value="0" ${!u.is_admin?'selected':''}>User</option>
                  <option value="1" ${u.is_admin?'selected':''}>Admin</option>
                </select></div>
            </div>
            <div style="display:flex;gap:8px;">
              <button class="btn primary" type="submit">Save Changes</button>
              <button class="btn" type="button" onclick="toggleEdit('leg_${esc(u.username)}')">Cancel</button>
            </div>
          </form>
        </div>
      </td>
    </tr>`).join('');

  // ── Access pairs ──
  const accessRows = accessList.map(a => `
    <tr>
      <td style="color:var(--text);font-size:11px;">${esc(a.viewer)}</td>
      <td style="color:var(--dim);font-size:12px;">→</td>
      <td style="color:var(--text);font-size:11px;">${esc(a.target)}</td>
      <td>
        <form method="POST" action="${BASE}/users/legacy/revoke-access" style="display:inline;">
          <input type="hidden" name="viewer" value="${esc(a.viewer)}"/>
          <input type="hidden" name="target" value="${esc(a.target)}"/>
          <button class="btn danger" style="padding:3px 10px;font-size:9px;" type="submit">Revoke</button>
        </form>
      </td>
    </tr>`).join('');

  const usernameOpts = usernames.map(u => `<option value="${esc(u)}">${esc(u)}</option>`).join('');

  const body = `
    <div class="page-title">Users</div>
    <div class="page-sub">§ Forge + Legacy · User Management</div>
    ${flash?`<div class="alert ${flash.type}">${esc(flash.msg)}</div>`:''}

    <div class="stat-row">
      <div class="stat-cell"><div class="stat-num">${users.length}</div><div class="stat-label">Forge Users</div></div>
      <div class="stat-cell"><div class="stat-num">${users.filter(u=>u.role==='admin').length}</div><div class="stat-label">Forge Admins</div></div>
      <div class="stat-cell"><div class="stat-num">${legacyUsers.length}</div><div class="stat-label">Legacy Users</div></div>
      <div class="stat-cell"><div class="stat-num">${legacyUsers.filter(u=>u.is_admin).length}</div><div class="stat-label">Legacy Admins</div></div>
      <div class="stat-cell"><div class="stat-num">${accessList.length}</div><div class="stat-label">Partner Links</div></div>
    </div>

    <!-- ── ADD FORGE USER ── -->
    <div class="section">
      <div class="section-hdr"><span class="sh-num">01</span><span class="sh-title">Add Forge User · bookforge.users</span><div class="sh-line"></div></div>
      <div class="form-wrap" style="padding:24px 32px;">
        <form method="POST" action="${BASE}/users/add">
          <div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr auto;gap:12px;align-items:end;">
            <div class="form-group" style="margin:0;"><label class="form-label">Name <span class="req">*</span></label>
              <input class="form-input" name="name" placeholder="username" required/></div>
            <div class="form-group" style="margin:0;"><label class="form-label">Email</label>
              <input class="form-input" name="email" type="email" placeholder="optional"/></div>
            <div class="form-group" style="margin:0;"><label class="form-label">Password <span class="req">*</span></label>
              <input class="form-input" name="password" type="password" required/></div>
            <div class="form-group" style="margin:0;"><label class="form-label">Role</label>
              <select class="form-select" name="role">
                <option value="user">User</option><option value="admin">Admin</option>
              </select></div>
            <button class="btn primary" type="submit" style="padding:10px 20px;">Add ↗</button>
          </div>
        </form>
      </div>
    </div>

    <!-- ── ADD LEGACY USER ── -->
    <div class="section">
      <div class="section-hdr"><span class="sh-num">02</span><span class="sh-title">Add Legacy User · VectraArchLegacy</span><div class="sh-line"></div></div>
      <div class="form-wrap" style="padding:24px 32px;">
        <form method="POST" action="${BASE}/users/legacy/add">
          <div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr 1fr auto;gap:12px;align-items:end;">
            <div class="form-group" style="margin:0;"><label class="form-label">Username <span class="req">*</span></label>
              <input class="form-input" name="username" placeholder="username" required/></div>
            <div class="form-group" style="margin:0;"><label class="form-label">First Name</label>
              <input class="form-input" name="firstName" placeholder="First"/></div>
            <div class="form-group" style="margin:0;"><label class="form-label">Last Name</label>
              <input class="form-input" name="lastName" placeholder="Last"/></div>
            <div class="form-group" style="margin:0;"><label class="form-label">Email</label>
              <input class="form-input" name="email" type="email" placeholder="optional"/></div>
            <div class="form-group" style="margin:0;"><label class="form-label">Password <span class="req">*</span></label>
              <input class="form-input" name="password" type="password" required/></div>
            <button class="btn primary" type="submit" style="padding:10px 20px;">Add ↗</button>
          </div>
        </form>
      </div>
    </div>

    <!-- ── FORGE USERS TABLE ── -->
    <div class="section">
      <div class="section-hdr"><span class="sh-num">03</span><span class="sh-title">Forge Users · ${users.length} Accounts</span><div class="sh-line"></div></div>
      <table>
        <thead><tr><th>Name / Email / ID</th><th>Type</th><th>Role</th><th>Status</th><th>Logins</th><th>Last Login</th><th>2FA</th><th>Actions</th></tr></thead>
        <tbody>${forgeRows}</tbody>
      </table>
    </div>

    <!-- ── LEGACY USERS TABLE ── -->
    <div class="section">
      <div class="section-hdr"><span class="sh-num">04</span><span class="sh-title">Legacy Users · VectraArchLegacy · ${legacyUsers.length} Accounts</span><div class="sh-line"></div></div>
      ${legacyUsers.length===0
        ? '<div style="padding:24px;background:var(--bg2);color:var(--dim);text-align:center;letter-spacing:0.1em;font-size:10px;">No Legacy users found</div>'
        : `<table>
            <thead><tr><th>Username / Name</th><th>Email</th><th>Role</th><th>Activity</th><th>2FA</th><th>Last Active</th><th>Actions</th></tr></thead>
            <tbody>${legacyRows}</tbody>
           </table>`}
    </div>

    <!-- ── PARTNER SHARING / ACCESS LINKS ── -->
    <div class="section">
      <div class="section-hdr"><span class="sh-num">05</span><span class="sh-title">Partner Sharing · Access Links · ${accessList.length} pairs</span><div class="sh-line"></div></div>
      <div class="form-wrap" style="padding:20px 32px 24px;">
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;">
          <div>
            <div class="form-label" style="margin-bottom:12px;font-size:10px;letter-spacing:0.15em;">GRANT ACCESS (viewer can see target's data)</div>
            <form method="POST" action="${BASE}/users/legacy/grant-access">
              <div style="display:grid;grid-template-columns:1fr 1fr auto;gap:10px;align-items:end;">
                <div><div class="form-label" style="margin-bottom:4px;">Viewer</div>
                  <select class="form-select" name="viewer"><option value="">— Select —</option>${usernameOpts}</select></div>
                <div><div class="form-label" style="margin-bottom:4px;">Can see →</div>
                  <select class="form-select" name="target"><option value="">— Select —</option>${usernameOpts}</select></div>
                <button class="btn primary" type="submit" style="padding:10px 16px;">Grant ↗</button>
              </div>
            </form>
          </div>
          <div>
            <div class="form-label" style="margin-bottom:12px;font-size:10px;letter-spacing:0.15em;">CURRENT LINKS · ${accessList.length} pairs</div>
            ${accessList.length===0
              ? '<div style="color:var(--dim);font-size:10px;padding:8px 0;">No partner links configured.</div>'
              : `<table style="width:100%;">
                  <thead><tr><th>Viewer</th><th></th><th>Target</th><th>Action</th></tr></thead>
                  <tbody>${accessRows}</tbody>
                 </table>`}
          </div>
        </div>
      </div>
    </div>

    <script>function toggleEdit(id){var el=document.getElementById('edit-'+id);el.style.display=el.style.display==='none'?'block':'none';}</script>`;

  res.send(layout('Users', 'users', body));
});

// ── USER ACTION ROUTES ────────────────────────────────────────────────────────
app.post(BASE + '/users/add', isAuth, async (req, res) => {
  const { name, email, password, role } = req.body;
  if (!name||!password) {
    req.session.flash = { type:'err', msg:'Name and password required' };
    return res.redirect(BASE + '/users');
  }
  const newId = 'm_' + Date.now();
  await pool.query(
    'INSERT INTO users (id,name,email,password,type,role,status,logins) VALUES ($1,$2,$3,$4,$5,$6,$7,0)',
    [newId, name, email||null, password, 'Manual', role==='admin'?'admin':'user', 'enabled']
  );
  await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)',
    ['user_add', `name:${name} role:${role}`, 'ok']);
  req.session.flash = { type:'ok', msg:`✓ User "${name}" created in bookforge` };
  res.redirect(BASE + '/users');
});

app.post(BASE + '/users/edit/:id', isAuth, async (req, res) => {
  const uid = req.params.id;
  const { name, role, email, password } = req.body;
  if (!name) { req.session.flash={type:'err',msg:'Name required'}; return res.redirect(BASE+'/users'); }
  await pool.query('UPDATE users SET name=$1,role=$2 WHERE id=$3',
    [name, role==='admin'?'admin':'user', uid]);
  if (email !== undefined) {
    await pool.query("UPDATE users SET email=$1 WHERE id=$2 AND type='Manual'", [email||null, uid]);
  }
  if (password && password.trim()) {
    await pool.query("UPDATE users SET password=$1 WHERE id=$2 AND type='Manual'", [password.trim(), uid]);
  }
  await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)',
    ['user_edit', `id:${uid} name:${name}`, 'ok']);
  req.session.flash = { type:'ok', msg:`✓ User "${name}" updated` };
  res.redirect(BASE + '/users');
});

app.post(BASE + '/users/toggle/:id', isAuth, async (req, res) => {
  const uid    = req.params.id;
  const status = req.body.status === 'disabled' ? 'disabled' : 'enabled';
  await pool.query('UPDATE users SET status=$1 WHERE id=$2', [status, uid]);
  await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)',
    ['user_toggle', `id:${uid} status:${status}`, 'ok']);
  req.session.flash = { type:'ok', msg:`✓ User ${status}` };
  res.redirect(BASE + '/users');
});

app.post(BASE + '/users/reset-2fa/:id', isAuth, async (req, res) => {
  await pool.query('UPDATE users SET twofa_secret=NULL WHERE id=$1', [req.params.id]);
  await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)',
    ['user_reset_2fa', `id:${req.params.id}`, 'ok']);
  req.session.flash = { type:'ok', msg:'✓ 2FA reset' };
  res.redirect(BASE + '/users');
});

app.post(BASE + '/users/delete/:id', isAuth, async (req, res) => {
  const uid = req.params.id;
  if (uid === req.session.conduitUser.id) {
    req.session.flash = { type:'err', msg:'Cannot delete your own account' };
    return res.redirect(BASE + '/users');
  }
  const u = await pool.query('SELECT name FROM users WHERE id=$1', [uid]);
  const name = u.rows[0]?.name || uid;
  await pool.query('DELETE FROM users WHERE id=$1', [uid]);
  await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)',
    ['user_delete', `id:${uid} name:${name}`, 'ok']);
  req.session.flash = { type:'ok', msg:`✓ User "${name}" deleted from bookforge` };
  res.redirect(BASE + '/users');
});


// ── LEGACY USER MANAGEMENT ROUTES ────────────────────────────────────────────

// POST: Add a new Legacy user
app.post(BASE + '/users/legacy/add', isAuth, async (req, res) => {
  const { username, firstName, lastName, email, password, isAdmin } = req.body;
  if (!username || !password) {
    req.session.flash = { type:'err', msg:'Username and password are required.' };
    return res.redirect(BASE + '/users');
  }
  try {
    const bcrypt = require('bcrypt');
    const hash = await bcrypt.hash(password, 10);
    await legacyPool.query(
      'INSERT INTO vectraarchlegacy_users (username, password_hash, first_name, last_name, display_name, email, is_admin) VALUES ($1,$2,$3,$4,$5,$6,$7)',
      [username.toLowerCase().trim(), hash, firstName||null, lastName||null,
       (firstName&&lastName)?`${firstName} ${lastName}`:username, email||null, isAdmin?1:0]
    );
    await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)',
      ['legacy_user_add', `username:${username}`, 'ok']);
    req.session.flash = { type:'ok', msg:`✓ Legacy user "${username}" created` };
  } catch(e) {
    req.session.flash = { type:'err', msg:`Error: ${e.message}` };
  }
  res.redirect(BASE + '/users');
});

// POST: Edit Legacy user fields
app.post(BASE + '/users/legacy/edit/:username', isAuth, async (req, res) => {
  const { username } = req.params;
  const { firstName, lastName, email, newUsername, isAdmin, password } = req.body;
  try {
    const displayName = (firstName&&lastName)?`${firstName} ${lastName}`:username;
    await legacyPool.query(
      `UPDATE vectraarchlegacy_users SET first_name=$1, last_name=$2, display_name=$3, email=$4, is_admin=$5 WHERE username=$6`,
      [firstName||null, lastName||null, displayName, email||null, isAdmin?1:0, username]
    );
    if (password && password.trim()) {
      const bcrypt = require('bcrypt');
      const hash = await bcrypt.hash(password.trim(), 10);
      await legacyPool.query('UPDATE vectraarchlegacy_users SET password_hash=$1 WHERE username=$2', [hash, username]);
    }
    await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)',
      ['legacy_user_edit', `username:${username}`, 'ok']);
    req.session.flash = { type:'ok', msg:`✓ Legacy user "${username}" updated` };
  } catch(e) {
    req.session.flash = { type:'err', msg:`Error: ${e.message}` };
  }
  res.redirect(BASE + '/users');
});

// POST: Delete Legacy user
app.post(BASE + '/users/legacy/delete/:username', isAuth, async (req, res) => {
  const { username } = req.params;
  try {
    await legacyPool.query('DELETE FROM vectraarchlegacy_users WHERE username=$1', [username]);
    await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)',
      ['legacy_user_delete', `username:${username}`, 'ok']);
    req.session.flash = { type:'ok', msg:`✓ Legacy user "${username}" deleted` };
  } catch(e) {
    req.session.flash = { type:'err', msg:`Error: ${e.message}` };
  }
  res.redirect(BASE + '/users');
});

// POST: Toggle Legacy user 2FA (reset secret = disable)
app.post(BASE + '/users/legacy/toggle-2fa/:username', isAuth, async (req, res) => {
  const { username } = req.params;
  const { action } = req.body; // 'disable'
  try {
    if (action === 'disable') {
      await legacyPool.query('UPDATE vectraarchlegacy_users SET twofa_secret=NULL WHERE username=$1', [username]);
      req.session.flash = { type:'ok', msg:`✓ 2FA disabled for "${username}"` };
    }
  } catch(e) {
    req.session.flash = { type:'err', msg:`Error: ${e.message}` };
  }
  res.redirect(BASE + '/users');
});

// POST: Grant Legacy access (partner sharing)
app.post(BASE + '/users/legacy/grant-access', isAuth, async (req, res) => {
  const { viewer, target } = req.body;
  if (!viewer||!target||viewer===target) {
    req.session.flash = { type:'err', msg:'Viewer and target must be different users.' };
    return res.redirect(BASE + '/users');
  }
  try {
    await legacyPool.query(
      'INSERT INTO vectraarchlegacy_access (viewer,target) VALUES ($1,$2) ON CONFLICT DO NOTHING',
      [viewer, target]
    );
    req.session.flash = { type:'ok', msg:`✓ Access granted: ${viewer} → ${target}` };
  } catch(e) {
    req.session.flash = { type:'err', msg:`Error: ${e.message}` };
  }
  res.redirect(BASE + '/users');
});

// POST: Revoke Legacy access
app.post(BASE + '/users/legacy/revoke-access', isAuth, async (req, res) => {
  const { viewer, target } = req.body;
  try {
    await legacyPool.query('DELETE FROM vectraarchlegacy_access WHERE viewer=$1 AND target=$2', [viewer, target]);
    req.session.flash = { type:'ok', msg:`✓ Access revoked: ${viewer} → ${target}` };
  } catch(e) {
    req.session.flash = { type:'err', msg:`Error: ${e.message}` };
  }
  res.redirect(BASE + '/users');
});

// ── START ─────────────────────────────────────────────────────────────────────
setupDB().then(() => {
  app.listen(PORT, HOST, () => {
    console.log(`[conduit] VectraArchConduit listening on ${HOST}:${PORT}`);
    console.log(`[conduit] Database: bookforge (${process.env.DB_USER}@${process.env.DB_HOST||'localhost'})`);
    console.log(`[conduit] Routes: ${BASE}/, ${BASE}/sites, ${BASE}/users, ${BASE}/login, ${BASE}/auth/2fa`);
  });
}).catch(e => { console.error('[conduit] DB setup failed:', e); process.exit(1); });