'use strict';

/**
 * Conduit Hub — VectraArch Automation, Social & Site Manager
 * Built on Express + express-session (same pattern as Book Forge)
 * so Foundation cross-domain auth works correctly.
 *
 * Port: 3100 (internal, nginx proxies)
 */

require('dotenv').config({ path: '/var/www/vectraarch.live/forge/.env' });
const pm2 = require('pm2');

const express        = require('express');
const session        = require('express-session');
const https          = require('https');
const fs             = require('fs');
const path           = require('path');
const { Pool }       = require('pg');
const { verify, generateSecret, generateURI } = require('otplib');
const qrcode         = require('qrcode');

const app  = express();
const PORT = 3100;
const HOST = '127.0.0.1';
const BASE = '/conduit'; // All routes and redirects prefixed here

const TELEGRAM_TOKEN   = '8767176406:AAEMhPAuQw5dFPEMcLEru1ZkqFT5ijk8YCk';
const TELEGRAM_CHAT_ID = '8783471876';
const PRESS_URL        = 'https://vectraarch.live/press';
const FORGE_URL        = 'https://vectraarch.live/forge';
const FOUNDATION_URL   = 'https://vectraarch.live/foundation/';
const WWW_ROOT         = '/var/www/vectraarch.live';

const pool = new Pool({
  user:     process.env.DB_USER,
  host:     process.env.DB_HOST,
  database: process.env.DB_NAME,
  password: process.env.DB_PASSWORD,
  port:     parseInt(process.env.DB_PORT || '5432'),
});

// ── MIDDLEWARE ────────────────────────────────────────────────────────────────
app.set('trust proxy', 1);
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(session({
  secret:            process.env.SESSION_SECRET,
  resave:            false,
  saveUninitialized: false,
  cookie:            { secure: true, sameSite: 'lax', maxAge: 86400000 },
}));

// ── AUTH MIDDLEWARE ───────────────────────────────────────────────────────────
function isAuth(req, res, next) {
  if (!req.session.conduitUser) return res.redirect(FOUNDATION_URL);
  if (req.session.needs2FA) return res.redirect(BASE + '/auth/2fa');
  next();
}

// ── DB SETUP ──────────────────────────────────────────────────────────────────
async function setupDB() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS conduit_log (
      id      SERIAL PRIMARY KEY,
      event   TEXT NOT NULL,
      payload TEXT,
      status  TEXT NOT NULL DEFAULT 'ok',
      created TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS conduit_sites (
      subdomain TEXT PRIMARY KEY,
      label     TEXT,
      purpose   TEXT,
      created   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated   TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  console.log('[conduit] DB ready');
}

// ── KNOWN SITES ───────────────────────────────────────────────────────────────
const KNOWN_SITES = [
  { subdomain: '',          path: '/',            label: 'Home',       num: '—',     type: 'static',    purpose: 'Central hub · personal brand · studio map' },
  { subdomain: 'fabric',    path: '/fabric/',     label: 'Fabric',     num: '01/08', type: 'static',    purpose: 'Technical infrastructure portfolio' },
  { subdomain: 'conduit',   path: null,           label: 'Conduit',    num: '02/08', type: 'node',      purpose: 'Automation & social hub · vectraarch.live/conduit/' },
  { subdomain: 'forge',     path: null,           label: 'Book Forge', num: '03/08', type: 'node',      purpose: 'Writing management application · vectraarch.live/forge/' },
  { subdomain: 'keystone',  path: '/keystone/',   label: 'Keystone',   num: '04/08', type: 'static',    purpose: 'Constellation architecture documentation' },
  { subdomain: 'kinetic',   path: '/kinetic/',    label: 'Kinetic',    num: '05/08', type: 'static',    purpose: 'Visual portfolio · sculpture · gaming' },
  { subdomain: 'volition',  path: '/volition/',   label: 'Volition',   num: '06/08', type: 'static',    purpose: "Builder's log · process journal" },
  { subdomain: 'foundation',path: '/foundation/', label: 'Foundation', num: '07/08', type: 'static',    purpose: 'Central auth hub' },
  { subdomain: 'press',     path: '/press/',      label: 'Press',      num: '08/08', type: 'generated', purpose: 'Auto-generated by Book Forge on publish' },
  { subdomain: 'bo7',       path: '/bo7/',        label: 'Bo7',        num: '—',     type: 'static',    purpose: 'CoD coaching platform · ZenithB_Actual' },
  { subdomain: 'legacy',    path: '/legacy/',     label: 'Legacy',     num: '—',     type: 'static',    purpose: 'Legacy lifestyle app' },
];


// ── API REGISTRY ──────────────────────────────────────────────────────────────
const API_REGISTRY = [
  // VectraArchForge
  { app: 'VectraArchForge', method: 'POST', path: '/forge/auth/manual',         desc: 'Manual login' },
  { app: 'VectraArchForge', method: 'GET',  path: '/forge/auth/google',         desc: 'Google OAuth' },
  { app: 'VectraArchForge', method: 'GET',  path: '/forge/auth/2fa',            desc: '2FA verify page' },
  { app: 'VectraArchForge', method: 'POST', path: '/forge/auth/2fa',            desc: '2FA submit' },
  { app: 'VectraArchForge', method: 'GET',  path: '/forge/auth/2fa/setup',      desc: '2FA setup page' },
  { app: 'VectraArchForge', method: 'POST', path: '/forge/auth/2fa/setup',      desc: '2FA activate' },
  { app: 'VectraArchForge', method: 'GET',  path: '/forge/logout',              desc: 'Logout' },
  { app: 'VectraArchForge', method: 'POST', path: '/forge/create-book',         desc: 'Create book' },
  { app: 'VectraArchForge', method: 'GET',  path: '/forge/book/:id',            desc: 'Open book' },
  { app: 'VectraArchForge', method: 'POST', path: '/forge/book/:id/publish',    desc: 'Publish to Press' },
  { app: 'VectraArchForge', method: 'POST', path: '/forge/book/:id/unpublish',  desc: 'Unpublish from Press' },
  { app: 'VectraArchForge', method: 'POST', path: '/forge/book/:id/add',        desc: 'Add entry to book' },
  { app: 'VectraArchForge', method: 'POST', path: '/forge/book/delete/:id',     desc: 'Delete book' },
  { app: 'VectraArchForge', method: 'GET',  path: '/forge/book/:id/export/:fmt',desc: 'Export book (docx/pdf/epub/md/txt)' },
  // VectraArchConduit
  { app: 'VectraArchConduit', method: 'POST', path: '/conduit/login',           desc: 'Login' },
  { app: 'VectraArchConduit', method: 'GET',  path: '/conduit/logout',          desc: 'Logout' },
  { app: 'VectraArchConduit', method: 'GET',  path: '/conduit/auth/2fa',        desc: '2FA verify page' },
  { app: 'VectraArchConduit', method: 'POST', path: '/conduit/auth/2fa',        desc: '2FA submit' },
  { app: 'VectraArchConduit', method: 'GET',  path: '/conduit/auth/2fa/setup',  desc: '2FA setup' },
  { app: 'VectraArchConduit', method: 'POST', path: '/conduit/announce',        desc: 'Telegram announcement' },
  { app: 'VectraArchConduit', method: 'GET',  path: '/conduit/sites',           desc: 'Site & API registry' },
  { app: 'VectraArchConduit', method: 'GET',  path: '/conduit/users',           desc: 'User management' },
  { app: 'VectraArchConduit', method: 'POST', path: '/conduit/log/clear',       desc: 'Clear event log' },
  // VectraArchLegacy
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/login',              desc: 'Authentication' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/verify-2fa',         desc: '2FA verify' },
  { app: 'VectraArchLegacy', method: 'GET',  path: '/legacy/api/2fa/status',         desc: '2FA status' },
  { app: 'VectraArchLegacy', method: 'GET',  path: '/legacy/api/2fa/setup',          desc: '2FA setup QR' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/2fa/setup',          desc: '2FA activate' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/2fa/disable',        desc: '2FA disable' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/2fa/reset',          desc: 'Admin 2FA reset' },
  { app: 'VectraArchLegacy', method: 'GET',  path: '/legacy/api/users',              desc: 'User list' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/add-user',           desc: 'Add user' },
  { app: 'VectraArchLegacy', method: 'DELETE',path: '/legacy/api/delete-user/:u',   desc: 'Delete user' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/grant-access',       desc: 'Grant access' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/revoke-access',      desc: 'Revoke access' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/grant-admin',        desc: 'Grant admin' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/revoke-admin',       desc: 'Revoke admin' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/admin-update-password', desc: 'Admin update password' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/update-password',    desc: 'User update password' },
  { app: 'VectraArchLegacy', method: 'GET',  path: '/legacy/api/financial',          desc: 'Get financial items' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/financial',          desc: 'Add financial item' },
  { app: 'VectraArchLegacy', method: 'GET',  path: '/legacy/api/budget',             desc: 'Get budgets' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/budget',             desc: 'Add budget' },
  { app: 'VectraArchLegacy', method: 'GET',  path: '/legacy/api/calendar',           desc: 'Get calendar events' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/calendar',           desc: 'Add calendar event' },
  { app: 'VectraArchLegacy', method: 'GET',  path: '/legacy/api/gymworkout',         desc: 'Get gym workouts' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/gymworkout',         desc: 'Add gym workout' },
  { app: 'VectraArchLegacy', method: 'GET',  path: '/legacy/api/mealplan',           desc: 'Get meal plans' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/mealplan',           desc: 'Add meal plan' },
  { app: 'VectraArchLegacy', method: 'GET',  path: '/legacy/api/period',             desc: 'Get period cycles' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/period',             desc: 'Add period cycle' },
  { app: 'VectraArchLegacy', method: 'GET',  path: '/legacy/api/profile-pictures',   desc: 'Get profile' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/profile-pictures',   desc: 'Update profile' },
  { app: 'VectraArchLegacy', method: 'GET',  path: '/legacy/api/notifications',      desc: 'Get notifications' },
  { app: 'VectraArchLegacy', method: 'POST', path: '/legacy/api/notifications',      desc: 'Update notifications' },
];

// ── HELPERS ───────────────────────────────────────────────────────────────────
function esc(s) {
  return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}
function postTelegram(text) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({ chat_id: TELEGRAM_CHAT_ID, text });
    const req = https.request(
      `https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage`,
      { method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) } },
      r => { let d=''; r.on('data',c=>d+=c); r.on('end',()=>{ try{resolve(JSON.parse(d));}catch{reject(new Error('Parse'));} }); }
    );
    req.on('error', reject); req.write(body); req.end();
  });
}
function siteIndexPath(sub) { return path.join(WWW_ROOT, sub, 'index.html'); }
function siteExists(sub) { try { return fs.existsSync(path.join(WWW_ROOT, sub)); } catch { return false; } }
function siteLastModified(sub) {
  try { return fs.statSync(siteIndexPath(sub)).mtime.toLocaleString('en-ZA'); } catch { return '—'; }
}
function readSite(sub) { try { return fs.readFileSync(siteIndexPath(sub), 'utf8'); } catch { return ''; } }
function writeSite(sub, html) {
  fs.mkdirSync(path.join(WWW_ROOT, sub), { recursive: true });
  fs.writeFileSync(siteIndexPath(sub), html, 'utf8');
}

// ── CSS / FONTS ───────────────────────────────────────────────────────────────
const FONTS = `<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Mono:wght@0,300;0,400;0,500&family=Barlow+Condensed:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>`;

const CSS = `
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0;}
:root{--bg:#0a0a08;--bg2:#111110;--bg3:#191917;--border:rgba(255,255,255,0.07);--border2:rgba(255,255,255,0.14);--text:#e8e4d8;--muted:rgba(232,228,216,0.5);--dim:rgba(232,228,216,0.22);--accent:#00ff41;--accent2:#00b32c;--red:#b84040;}
html{scroll-behavior:smooth;}
body{background:var(--bg);color:var(--text);font-family:DM Mono,monospace;font-size:13px;line-height:1.7;overflow-x:hidden;}
body::before{content:'';position:fixed;inset:0;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 512 512' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.75' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.035'/%3E%3C/svg%3E");opacity:0.4;pointer-events:none;z-index:0;}
.grid-bg{position:fixed;inset:0;background-image:linear-gradient(var(--border) 1px,transparent 1px),linear-gradient(90deg,var(--border) 1px,transparent 1px);background-size:80px 80px;pointer-events:none;z-index:0;}
.accent-lines{position:fixed;top:0;right:0;width:50%;height:100%;pointer-events:none;overflow:hidden;z-index:0;}
.accent-lines svg{width:100%;height:100%;}
nav{position:fixed;top:0;left:0;right:0;z-index:100;display:flex;align-items:center;justify-content:space-between;padding:0 32px;height:56px;border-bottom:1px solid var(--border);background:rgba(10,10,8,0.92);backdrop-filter:blur(12px);}
.nav-logo{font-family:'Barlow Condensed',sans-serif;font-weight:700;font-size:14px;letter-spacing:0.22em;text-transform:uppercase;color:var(--text);text-decoration:none;}
.nav-logo span{color:var(--accent);}
.nav-tabs{display:flex;align-items:center;gap:0;}
.nav-tab{font-size:10px;letter-spacing:0.14em;text-transform:uppercase;color:var(--dim);text-decoration:none;padding:0 16px;height:56px;display:flex;align-items:center;border-bottom:2px solid transparent;transition:color 0.2s,border-color 0.2s;}
.nav-tab:hover{color:var(--muted);}
.nav-tab.active{color:var(--accent);border-bottom-color:var(--accent);}
.nav-right{display:flex;align-items:center;gap:16px;}
.nav-status{display:flex;align-items:center;gap:7px;font-size:10px;letter-spacing:0.1em;color:var(--dim);}
.nav-status::before{content:'';display:block;width:6px;height:6px;border-radius:50%;background:var(--accent);box-shadow:0 0 6px var(--accent);}
.nav-link{font-size:10px;letter-spacing:0.14em;text-transform:uppercase;color:var(--dim);text-decoration:none;transition:color 0.2s;}
.nav-link:hover{color:var(--muted);}
.wrap{position:relative;z-index:1;padding:80px 32px 60px;max-width:1200px;margin:0 auto;}
.page-title{font-family:'Bebas Neue',sans-serif;font-size:56px;line-height:0.9;color:var(--text);letter-spacing:0.02em;margin-bottom:6px;}
.page-sub{font-size:10px;letter-spacing:0.2em;text-transform:uppercase;color:var(--dim);margin-bottom:40px;}
.stat-row{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--border);margin-bottom:40px;}
.stat-cell{background:var(--bg2);padding:24px 20px;}
.stat-num{font-family:'Bebas Neue',sans-serif;font-size:2.4rem;line-height:1;color:var(--accent);margin-bottom:4px;}
.stat-num.r{color:var(--red);}
.stat-label{font-size:9px;letter-spacing:0.18em;text-transform:uppercase;color:var(--dim);}
.section{margin-bottom:40px;}
.section-hdr{display:flex;align-items:baseline;gap:16px;margin-bottom:20px;padding-bottom:12px;border-bottom:1px solid var(--border);}
.sh-num{font-size:10px;letter-spacing:0.2em;color:var(--dim);}
.sh-title{font-family:'Barlow Condensed',sans-serif;font-size:11px;font-weight:500;letter-spacing:0.28em;text-transform:uppercase;color:var(--muted);}
.sh-line{flex:1;height:1px;background:var(--border);}
table{width:100%;border-collapse:collapse;background:var(--bg2);}
th{font-size:9px;letter-spacing:0.18em;text-transform:uppercase;color:var(--dim);padding:12px 16px;text-align:left;border-bottom:1px solid var(--border2);}
td{padding:14px 16px;border-bottom:1px solid var(--border);color:var(--muted);font-size:12px;vertical-align:middle;}
tr:last-child td{border-bottom:none;}
tr:hover td{background:var(--bg3);}
.badge{display:inline-block;font-size:9px;letter-spacing:0.14em;text-transform:uppercase;padding:3px 10px;border:1px solid;}
.badge.ok{color:var(--accent);border-color:rgba(0,255,65,0.25);background:rgba(0,255,65,0.05);}
.badge.err{color:var(--red);border-color:rgba(184,64,64,0.25);background:rgba(184,64,64,0.05);}
.badge.info{color:var(--muted);border-color:var(--border2);}
.badge.warn{color:#d4a800;border-color:rgba(212,168,0,0.25);background:rgba(212,168,0,0.05);}
.btn{display:inline-flex;align-items:center;gap:8px;font-family:DM Mono,monospace;font-size:10px;letter-spacing:0.16em;text-transform:uppercase;color:var(--text);background:none;border:1px solid var(--border2);padding:8px 16px;cursor:pointer;transition:border-color 0.2s,color 0.2s;text-decoration:none;}
.btn:hover{border-color:var(--accent);color:var(--accent);}
.btn.primary{background:var(--accent);color:#0a0a08;border-color:var(--accent);}
.btn.primary:hover{background:var(--accent2);border-color:var(--accent2);color:#fff;}
.btn.danger{border-color:rgba(184,64,64,0.4);color:var(--red);}
.btn.danger:hover{border-color:var(--red);}
.alert{padding:12px 16px;border:1px solid;font-size:11px;letter-spacing:0.08em;margin-bottom:20px;}
.alert.ok{color:var(--accent);border-color:rgba(0,255,65,0.25);background:rgba(0,255,65,0.05);}
.alert.err{color:var(--red);border-color:rgba(184,64,64,0.25);background:rgba(184,64,64,0.05);}
.form-wrap{background:var(--bg2);border:1px solid var(--border2);padding:32px;}
.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 32px;}
.form-group{display:flex;flex-direction:column;gap:6px;margin-bottom:24px;}
.form-group.full{grid-column:1/-1;}
.form-label{font-size:9px;letter-spacing:0.22em;text-transform:uppercase;color:var(--dim);}
.form-label .req{color:var(--red);}
.form-input,.form-select,.form-textarea{background:var(--bg);border:1px solid var(--border2);color:var(--text);font-family:DM Mono,monospace;font-size:12px;letter-spacing:0.06em;padding:10px 14px;outline:none;transition:border-color 0.2s;width:100%;}
.form-input:focus,.form-select:focus,.form-textarea:focus{border-color:var(--accent);}
.form-input::placeholder,.form-textarea::placeholder{color:var(--dim);}
.form-textarea{resize:vertical;min-height:80px;}
.form-select{cursor:pointer;-webkit-appearance:none;}
.form-hint{font-size:9px;letter-spacing:0.1em;color:var(--dim);margin-top:4px;}
.form-section{margin-bottom:32px;padding-bottom:32px;border-bottom:1px solid var(--border);}
.form-section:last-of-type{border-bottom:none;}
.form-section-title{font-family:'Barlow Condensed',sans-serif;font-size:13px;font-weight:600;letter-spacing:0.2em;text-transform:uppercase;color:var(--muted);margin-bottom:20px;}
.form-actions{display:flex;gap:12px;padding-top:20px;border-top:1px solid var(--border);}
.narrative-block{background:var(--bg3);border:1px solid var(--border);padding:20px;margin-bottom:12px;}
.narrative-block-title{font-size:9px;letter-spacing:0.2em;text-transform:uppercase;color:var(--accent2);margin-bottom:14px;}
.code-block{background:var(--bg3);border:1px solid var(--border2);padding:20px 24px;font-family:DM Mono,monospace;font-size:12px;color:var(--accent);letter-spacing:0.06em;line-height:2;white-space:pre;overflow-x:auto;}
.login-wrap{min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:40px;position:relative;z-index:1;}
.login-card{width:100%;max-width:400px;border:1px solid var(--border2);background:var(--bg2);padding:44px 36px;position:relative;}
.login-card::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;background:var(--accent);}
.login-eyebrow{font-size:9px;letter-spacing:0.28em;text-transform:uppercase;color:var(--accent);margin-bottom:12px;}
.login-title{font-family:'Bebas Neue',sans-serif;font-size:56px;line-height:0.9;color:var(--text);margin-bottom:4px;}
.login-sub{font-family:'Barlow Condensed',sans-serif;font-weight:300;font-size:12px;letter-spacing:0.1em;text-transform:uppercase;color:var(--muted);margin-bottom:32px;}
.field{display:flex;flex-direction:column;gap:6px;margin-bottom:20px;}
.field label{font-size:9px;letter-spacing:0.22em;text-transform:uppercase;color:var(--dim);}
.field input{background:transparent;border:none;border-bottom:1px solid var(--border2);padding:10px 0;font-family:DM Mono,monospace;font-size:13px;color:var(--text);outline:none;transition:border-color 0.2s;width:100%;}
.field input:focus{border-bottom-color:var(--accent);}
.field input::placeholder{color:var(--dim);}
.login-err{font-size:10px;letter-spacing:0.1em;color:var(--red);margin-top:12px;padding:10px 0;border-top:1px solid rgba(184,64,64,0.2);}
@media(max-width:768px){.stat-row{grid-template-columns:1fr 1fr;}.wrap{padding:72px 20px 40px;}.form-grid{grid-template-columns:1fr;}}
`;


// ── PM2 STATUS HELPER ─────────────────────────────────────────────────────────
function getPM2List() {
  return new Promise((resolve) => {
    pm2.connect(true, (err) => {
      if (err) return resolve([]);
      pm2.list((err, list) => {
        pm2.disconnect();
        if (err) return resolve([]);
        resolve(list.map(p => ({
          name: p.name,
          status: p.pm2_env.status,
          pid: p.pid,
          uptime: p.pm2_env.pm_uptime ? Math.floor((Date.now() - p.pm2_env.pm_uptime) / 1000) : 0,
          restarts: p.pm2_env.restart_time,
          memory: p.monit ? Math.round(p.monit.memory / 1024 / 1024) : 0,
          cpu: p.monit ? p.monit.cpu : 0,
          script: p.pm2_env.pm_exec_path || ''
        })));
      });
    });
  });
}

function formatUptime(seconds) {
  if (seconds < 60) return seconds + 's';
  if (seconds < 3600) return Math.floor(seconds/60) + 'm';
  if (seconds < 86400) return Math.floor(seconds/3600) + 'h ' + Math.floor((seconds%3600)/60) + 'm';
  return Math.floor(seconds/86400) + 'd ' + Math.floor((seconds%86400)/3600) + 'h';
}

function layout(title, activeTab, body) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>${esc(title)} · Conduit</title>${FONTS}<style>${CSS}</style></head><body>
<div class="grid-bg"></div>
<nav>
  <a href="${BASE}/" class="nav-logo">Vectra<span>&nbsp;</span>Arch · Conduit</a>
  <div class="nav-tabs">
    <a href="${BASE}/" class="nav-tab ${activeTab==='dashboard'?'active':''}">Dashboard</a>
    <a href="${BASE}/sites" class="nav-tab ${activeTab==='sites'?'active':''}">Observatory</a>
    <a href="${BASE}/users" class="nav-tab ${activeTab==='users'?'active':''}">Users</a>
  </div>
  <div class="nav-right">
    <div class="nav-status">HUB · LIVE</div>
    <a href="${FORGE_URL}" class="nav-link" target="_blank">Forge ↗</a>
    <a href="${BASE}/logout" class="nav-link">Logout</a>
  </div>
</nav>
<div class="wrap">${body}</div>
</body></html>`;
}

// ── VA.CSS PAGE BUILDER ───────────────────────────────────────────────────────
function buildVAPage(data) {
  const { subdomain, studioNum, siteTitle, metaDesc, eyebrow, heroTitle, heroTitleGhost,
          heroTagline, coords, sections, footerLogo, footerLinks, terminalPrompt, terminalCmd } = data;

  const navStatus = studioNum ? `${(siteTitle||subdomain).toUpperCase()} · ${studioNum}` : (siteTitle||subdomain).toUpperCase();

  const coordsHtml = (coords||[]).filter(c=>c.key&&c.value).map(c=>
    `      <div class="coord"><span class="key">${esc(c.key)}</span><span>${esc(c.value)}</span></div>`
  ).join('\n');

  const sectionsHtml = (sections||[]).filter(s=>s.title).map(s => {
    const narrativesHtml = (s.narratives||[]).filter(n=>n.heading).map(n=>`
  <div class="narrative reveal">
    <div class="narrative-tag">${esc(n.tag||'')}<span class="year">${esc(n.year||'')}</span></div>
    <div>
      <div class="narrative-heading">${esc(n.heading)}</div>
      ${n.body1?`<p class="narrative-text">${esc(n.body1)}</p>`:''}
      ${n.body2?`<p class="narrative-text">${esc(n.body2)}</p>`:''}
    </div>
  </div>`).join('\n');
    return `
<section class="section">
  <div class="section-header reveal">
    <span class="sn">${esc(s.num||'§')}</span>
    <span class="st">${esc(s.title)}</span>
    <div class="sr"></div>
  </div>
  ${narrativesHtml}
</section>`;
  }).join('\n');

  const footerLinksHtml = (footerLinks||[]).filter(l=>l.label&&l.url).map(l=>
    `    <li><a href="${esc(l.url)}">${esc(l.label)}</a></li>`
  ).join('\n');

  const terminalHtml = (terminalPrompt||terminalCmd) ? `
<section class="section" style="padding-top:0;">
  <div class="terminal reveal">
    <div class="terminal-header">
      <div class="td"></div><div class="td"></div><div class="td"></div>
      <span class="tp">${esc(terminalPrompt||'schalk@vectraarch:~')} $</span>
    </div>
    <div class="tl"><span class="p">→ </span><span class="c">${esc(terminalCmd||'')}</span><span class="cursor" style="display:inline-block;width:8px;height:0.9em;background:var(--accent);vertical-align:middle;animation:blink 1.1s step-end infinite;"></span></div>
  </div>
</section>` : '';

  return `<!DOCTYPE html>
<html lang="en" id="top">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>${esc(siteTitle||subdomain)} · Vectra Arch</title>
  <meta name="description" content="${esc(metaDesc||'')}"/>
  <link rel="preconnect" href="https://fonts.googleapis.com"/>
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
  <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300&family=Barlow:wght@300;400;500;600&family=Barlow+Condensed:wght@300;400;500;700;800&display=swap" rel="stylesheet"/>
  <link rel="stylesheet" href="https://vectraarch.live/shared/va.css"/>
</head>
<body>
<div class="grid-bg"></div>
<div class="accent-lines" aria-hidden="true">
  <svg viewBox="0 0 600 900" fill="none" preserveAspectRatio="xMaxYMid slice">
    <line x1="580" y1="0" x2="20" y2="900" stroke="rgba(0,255,65,0.07)" stroke-width="1"/>
    <line x1="540" y1="0" x2="0" y2="760" stroke="rgba(0,255,65,0.05)" stroke-width="0.5"/>
    <line x1="600" y1="200" x2="100" y2="900" stroke="rgba(0,255,65,0.04)" stroke-width="1"/>
    <rect x="460" y="80" width="100" height="1" fill="rgba(0,255,65,0.15)"/>
    <rect x="480" y="120" width="60" height="1" fill="rgba(0,255,65,0.1)"/>
    <rect x="500" y="160" width="40" height="1" fill="rgba(0,255,65,0.07)"/>
    <circle cx="540" cy="180" r="60" stroke="rgba(0,255,65,0.04)" stroke-width="1" fill="none"/>
    <circle cx="540" cy="180" r="90" stroke="rgba(0,255,65,0.025)" stroke-width="0.5" fill="none"/>
    <circle cx="540" cy="180" r="130" stroke="rgba(0,255,65,0.015)" stroke-width="0.5" fill="none"/>
  </svg>
</div>
<nav>
  <a href="https://vectraarch.live" class="nav-logo">Vectra<span>&nbsp;</span>Arch</a>
  <div class="nav-path">
    <a href="https://vectraarch.live">vectraarch.live</a>
    <span class="sep">/</span>
    <span class="leaf">${esc(subdomain.replace('.vectraarch.live',''))}</span>
  </div>
  <div class="nav-status">${esc(navStatus)}</div>
</nav>
<div class="terminal-path-hero">
  <div class="tph">
    <span class="prompt">schalk@vectraarch</span>:~/${esc(subdomain.replace('.vectraarch.live',''))}$ <span class="cmd">cat index.md</span><span class="cursor"></span>
  </div>
</div>
<section class="hero">
  <p class="hero-label">§ ${esc(eyebrow||'')}</p>
  <h1 class="hero-title">
    ${esc(heroTitle||siteTitle||'')}
    ${heroTitleGhost?`<em>${esc(heroTitleGhost)}</em>`:''}
  </h1>
  <div class="hero-bottom">
    <div class="hero-tagline reveal">${esc(heroTagline||'').replace(/\n/g,'<br/>')}</div>
    <div class="hero-coords reveal">
${coordsHtml}
    </div>
  </div>
</section>
${sectionsHtml}
${terminalHtml}
<footer>
  <div class="footer-logo">${esc(footerLogo||siteTitle||subdomain)} · Vectra Arch</div>
  <ul class="footer-links">
${footerLinksHtml}
  </ul>
  <div class="footer-meta">Built on Linux · 2026</div>
</footer>
<a href="#top" class="back-to-top" id="btt" title="Back to top">↑</a>
<script>
  const obs=new IntersectionObserver(entries=>{entries.forEach((e,i)=>{if(e.isIntersecting){setTimeout(()=>e.target.classList.add('visible'),i*70);obs.unobserve(e.target);}});},{threshold:0.05,rootMargin:'0px 0px -30px 0px'});
  document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));
  const btt=document.getElementById('btt');
  window.addEventListener('scroll',()=>{btt.classList.toggle('visible',window.scrollY>400);});
</script>
</body>
</html>`;
}

function buildNginxConfig(subdomain) {
  // All static sites now live under vectraarch.live/{path} — no separate nginx config needed.
  // New subdomains created here just need a folder + index.html under /var/www/vectraarch.live/
  return `# No separate nginx config needed.
# Add a location block to /etc/nginx/sites-enabled/vectraarch.live:
#
#   location /${subdomain}/ {
#       try_files $uri $uri/ /${subdomain}/index.html;
#   }
#
# Then: nginx -t && systemctl reload nginx`;
}

function parseFormToSiteData(body, subdomain) {
  const coords = [1,2,3,4,5,6].map(i=>({ key: body[`coord${i}key`]||'', value: body[`coord${i}val`]||'' })).filter(c=>c.key&&c.value);
  const sections = [1,2,3,4].map(si=>{
    const title = body[`sec${si}title`]||'';
    if (!title) return null;
    const narratives = [1,2,3].map(ni=>({
      tag: body[`sec${si}n${ni}tag`]||'', year: body[`sec${si}n${ni}year`]||'',
      heading: body[`sec${si}n${ni}heading`]||'', body1: body[`sec${si}n${ni}body1`]||'', body2: body[`sec${si}n${ni}body2`]||'',
    })).filter(n=>n.heading);
    return { num: body[`sec${si}num`]||`0${si}`, title, narratives };
  }).filter(Boolean);
  const footerLinks = [1,2,3].map(i=>({ label: body[`fl${i}label`]||'', url: body[`fl${i}url`]||'' })).filter(l=>l.label&&l.url);
  return {
    subdomain, siteTitle: body.siteTitle||'', studioNum: body.studioNum||'',
    metaDesc: body.metaDesc||'', eyebrow: body.eyebrow||'',
    heroTitle: body.heroTitle||'', heroTitleGhost: body.heroTitleGhost||'',
    heroTagline: body.heroTagline||'', coords, sections,
    terminalPrompt: body.terminalPrompt||'', terminalCmd: body.terminalCmd||'',
    footerLogo: body.footerLogo||'', footerLinks,
  };
}

// ── AUTH ROUTES ───────────────────────────────────────────────────────────────
app.get(BASE + '/login', (req, res) => {
  if (req.session.conduitUser) return res.redirect(BASE + '/');
  res.send(loginPage());
});

app.post(BASE + '/login', async (req, res) => {
  const { cid, ak } = req.body;
  try {
    const r = await pool.query(
      `SELECT * FROM users WHERE LOWER(name)=LOWER($1) AND password=$2 AND role='admin'`,
      [cid||'', ak||'']
    );
    if (r.rows[0]?.status === 'enabled') {
      req.session.conduitUser = { id: r.rows[0].id, name: r.rows[0].name };
      await pool.query('UPDATE users SET logins=logins+1, last_login=$1 WHERE id=$2',
        [new Date().toLocaleString('en-ZA'), r.rows[0].id]);
      if (r.rows[0].twofa_secret) {
        req.session.needs2FA = true;
        return res.redirect(BASE + '/auth/2fa');
      }
      return res.redirect(BASE + '/');
    }
    res.send(loginPage('Invalid credentials'));
  } catch(e) {
    console.error('[conduit] Login error:', e);
    res.send(loginPage('System error — try again'));
  }
});

app.get(BASE + '/logout', (req, res) => {
  req.session.destroy();
  res.redirect(FOUNDATION_URL);
});

// ── 2FA ───────────────────────────────────────────────────────────────────────
app.get(BASE + '/auth/2fa', (req, res) => {
  if (!req.session.conduitUser) return res.redirect(FOUNDATION_URL);
  if (!req.session.needs2FA) return res.redirect(BASE + '/');
  res.send(twoFAVerifyPage());
});

app.post(BASE + '/auth/2fa', async (req, res) => {
  if (!req.session.conduitUser) return res.redirect(FOUNDATION_URL);
  const u = await pool.query('SELECT twofa_secret FROM users WHERE id=$1', [req.session.conduitUser.id]);
  const secret = u.rows[0]?.twofa_secret;
  if (!secret) { delete req.session.needs2FA; return res.redirect(BASE + '/'); }
  try {
    if (verify({ token: req.body.token||'', secret })) {
      delete req.session.needs2FA;
      return res.redirect(BASE + '/');
    }
    res.send(twoFAVerifyPage('Invalid code — try again'));
  } catch { delete req.session.needs2FA; res.redirect(BASE + '/'); }
});

app.get(BASE + '/auth/2fa/setup', isAuth, async (req, res) => {
  const u = await pool.query('SELECT twofa_secret FROM users WHERE id=$1', [req.session.conduitUser.id]);
  if (u.rows[0]?.twofa_secret) return res.redirect(BASE + '/');
  const secret = generateSecret();
  req.session.tempSecret = secret;
  const qr = await qrcode.toDataURL(generateURI({ secret, label: req.session.conduitUser.id, issuer: 'ConduitHub' }));
  res.send(await twoFASetupPage(qr, secret));
});

app.post(BASE + '/auth/2fa/setup', isAuth, async (req, res) => {
  if (!req.session.tempSecret) return res.redirect(BASE + '/');
  if (verify({ token: req.body.token||'', secret: req.session.tempSecret })) {
    await pool.query('UPDATE users SET twofa_secret=$1 WHERE id=$2', [req.session.tempSecret, req.session.conduitUser.id]);
    delete req.session.tempSecret;
    req.session.flash = { type: 'ok', msg: '✓ Two-factor authentication enabled' };
    return res.redirect(BASE + '/');
  }
  const qr = await qrcode.toDataURL(generateURI({ secret: req.session.tempSecret, label: req.session.conduitUser.id, issuer: 'ConduitHub' }));
  res.send(await twoFASetupPage(qr, req.session.tempSecret, 'Invalid code — try again'));
});

app.post(BASE + '/auth/2fa/disable', isAuth, async (req, res) => {
  await pool.query('UPDATE users SET twofa_secret=NULL WHERE id=$1', [req.session.conduitUser.id]);
  req.session.flash = { type: 'ok', msg: '✓ Two-factor authentication disabled' };
  res.redirect(BASE + '/');
});

// ── DASHBOARD ─────────────────────────────────────────────────────────────────
app.get(BASE + '/', isAuth, async (req, res) => {
  const flash = req.session.flash; delete req.session.flash;
  const userRow = await pool.query('SELECT twofa_secret FROM users WHERE id=$1', [req.session.conduitUser.id]);
  const has2FA = !!userRow.rows[0]?.twofa_secret;
  const books = await pool.query(`
    SELECT b.id, b.title, u.name as author_name,
           (SELECT created FROM conduit_log WHERE payload LIKE '%' || b.id || '%' AND event='announcement' ORDER BY created DESC LIMIT 1) as last_announced
    FROM books b JOIN users u ON b.owner_id=u.id WHERE b.published=true ORDER BY u.name ASC, b.title ASC
  `);
  const logs = await pool.query('SELECT id,event,payload,status,created FROM conduit_log ORDER BY created DESC LIMIT 20');

  const bookRows = books.rows.map(b=>`
    <tr>
      <td style="color:var(--text)">${esc(b.title)}</td>
      <td>${esc(b.author_name)}</td>
      <td><span class="badge ok">Published</span></td>
      <td style="font-size:10px;color:var(--dim)">${b.last_announced?new Date(b.last_announced).toLocaleString('en-ZA'):'—'}</td>
      <td>
        <form method="POST" action="${BASE}/announce" style="display:inline;">
          <input type="hidden" name="book_id" value="${esc(b.id)}"/>
          <input type="hidden" name="book_title" value="${esc(b.title)}"/>
          <input type="hidden" name="author_name" value="${esc(b.author_name)}"/>
          <button class="btn" type="submit">Post ↗</button>
        </form>
      </td>
    </tr>`).join('');

  const logRows = logs.rows.map(l=>`
    <tr>
      <td style="font-size:10px;">${new Date(l.created).toLocaleString('en-ZA')}</td>
      <td><span class="badge ${l.status==='ok'?'ok':'err'}">${esc(l.event)}</span></td>
      <td style="font-size:11px;max-width:400px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">${esc(l.payload||'')}</td>
      <td><span class="badge ${l.status==='ok'?'ok':'err'}">${esc(l.status)}</span></td>
    </tr>`).join('');

  const body = `
    <div class="page-title">Conduit</div>
    <div class="page-sub">§ Automation &amp; Social Hub · VectraArch</div>
    ${flash?`<div class="alert ${flash.type}">${esc(flash.msg)}</div>`:''}
    <div class="stat-row">
      <div class="stat-cell"><div class="stat-num">${books.rows.length}</div><div class="stat-label">Published Volumes</div></div>
      <div class="stat-cell"><div class="stat-num">${logs.rows.filter(l=>l.event==='announcement').length}</div><div class="stat-label">Announcements</div></div>
      <div class="stat-cell"><div class="stat-num">${logs.rows.filter(l=>l.status==='ok').length}</div><div class="stat-label">Successful Triggers</div></div>
      <div class="stat-cell"><div class="stat-num r">${logs.rows.filter(l=>l.status==='err').length}</div><div class="stat-label">Failed Triggers</div></div>
    </div>
    <div class="section">
      <div class="section-hdr"><span class="sh-num">00</span><span class="sh-title">Your Account · Two-Factor Authentication</span><div class="sh-line"></div></div>
      <div style="background:var(--bg2);border:1px solid var(--border2);padding:24px 28px;display:flex;align-items:center;justify-content:space-between;gap:20px;">
        <div>
          <div style="font-family:'Barlow Condensed',sans-serif;font-weight:600;font-size:15px;letter-spacing:0.06em;text-transform:uppercase;color:var(--text);margin-bottom:6px;">
            2FA: <span style="color:${has2FA?'var(--accent)':'var(--red)'};">${has2FA?'Enabled':'Disabled'}</span>
          </div>
          <div style="font-size:11px;color:var(--dim);letter-spacing:0.08em;">${has2FA?'Your account is protected with two-factor authentication.':'Add an extra layer of security to your account.'}</div>
        </div>
        <div>${has2FA
          ?`<form method="POST" action="${BASE}/auth/2fa/disable"><button class="btn danger" type="submit" onclick="return confirm('Disable 2FA?')">Disable 2FA</button></form>`
          :`<a href="${BASE}/auth/2fa/setup" class="btn primary">Enable 2FA ↗</a>`}
        </div>
      </div>
    </div>
    <div class="section">
      <div class="section-hdr"><span class="sh-num">01</span><span class="sh-title">Published Volumes · Post Announcement</span><div class="sh-line"></div></div>
      ${books.rows.length===0
        ?'<div style="padding:32px;background:var(--bg2);color:var(--dim);text-align:center;letter-spacing:0.1em;">No published volumes</div>'
        :`<table><thead><tr><th>Title</th><th>Author</th><th>Status</th><th>Last Announced</th><th>Action</th></tr></thead><tbody>${bookRows}</tbody></table>`}
    </div>
    <div class="section">
      <div class="section-hdr"><span class="sh-num">02</span><span class="sh-title">Trigger Log · Last 20 Events</span><div class="sh-line"></div>
        <form method="POST" action="${BASE}/log/clear" style="margin-left:auto;"><button class="btn danger" type="submit" onclick="return confirm('Clear all logs?')">Clear Log</button></form>
      </div>
      ${logs.rows.length===0
        ?'<div style="padding:32px;background:var(--bg2);color:var(--dim);text-align:center;letter-spacing:0.1em;">No events logged yet</div>'
        :`<table><thead><tr><th>Time</th><th>Event</th><th>Payload</th><th>Status</th></tr></thead><tbody>${logRows}</tbody></table>`}
    </div>`;

  res.send(layout('Dashboard', 'dashboard', body));
});

app.post(BASE + '/announce', isAuth, async (req, res) => {
  const { book_id, book_title, author_name } = req.body;
  const text = `📖 New Publication · Vectra Arch Press\n\n"${book_title}"\nby ${author_name}\n\nRead it now → ${PRESS_URL}`;
  try {
    const tgRes = await postTelegram(text);
    await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)',
      ['announcement', `book_id:${book_id} title:${book_title} author:${author_name}`, tgRes.ok?'ok':'err']);
    req.session.flash = { type:'ok', msg:`✓ Announcement posted for "${book_title}"` };
  } catch(e) {
    await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)',
      ['announcement', `book_id:${book_id} ERROR:${e.message}`, 'err']);
    req.session.flash = { type:'err', msg:`✗ Failed: ${e.message}` };
  }
  res.redirect(BASE + '/');
});

app.post(BASE + '/log/clear', isAuth, async (req, res) => {
  await pool.query('DELETE FROM conduit_log');
  req.session.flash = { type:'ok', msg:'✓ Log cleared' };
  res.redirect(BASE + '/');
});

// ── SITES ─────────────────────────────────────────────────────────────────────
app.get(BASE + '/sites', isAuth, async (req, res) => {
  const flash = req.session.flash; delete req.session.flash;

  // PM2 process list
  const processes = await getPM2List();

  // Build PM2 status rows
  const pm2Rows = processes.map(p => {
    const isOnline = p.status === 'online';
    const statusBadge = isOnline
      ? `<span class="badge ok">Online</span>`
      : `<span class="badge err">${p.status}</span>`;
    return `<tr>
      <td style="color:var(--text);font-weight:500">${esc(p.name)}</td>
      <td>${statusBadge}</td>
      <td style="font-size:10px;color:var(--dim)">${p.pid||'—'}</td>
      <td style="font-size:10px;color:var(--dim)">${isOnline?formatUptime(p.uptime):'—'}</td>
      <td style="font-size:10px;color:var(--dim)">${p.restarts}</td>
      <td style="font-size:10px;color:${p.memory>200?'var(--red)':'var(--text-muted)'}">${p.memory} MB</td>
      <td style="font-size:10px;color:var(--dim)">${p.cpu}%</td>
    </tr>`;
  }).join('');

  // Build site rows (read-only, no New Site / Edit buttons)
  const siteRows = KNOWN_SITES.map(s => {
    const modified = s.subdomain ? siteLastModified(s.subdomain) : siteLastModified('');
    const url = s.path ? `https://vectraarch.live${s.path}` :
                s.subdomain === 'forge' ? 'https://vectraarch.live/forge/' :
                s.subdomain === 'conduit' ? 'https://vectraarch.live/conduit/' : '#';
    const typeBadge = s.type==='static'?`<span class="badge ok">Static</span>`
                    : s.type==='node'?`<span class="badge info">Node.js</span>`
                    : s.type==='generated'?`<span class="badge warn">Auto-gen</span>`
                    :`<span class="badge info">Proxy</span>`;
    const displayName = s.path ? `vectraarch.live${s.path}` :
                        s.subdomain === 'forge' ? 'vectraarch.live/forge/' :
                        s.subdomain === 'conduit' ? 'vectraarch.live/conduit/' : s.subdomain;
    return `<tr>
      <td><a href="${url}" target="_blank" style="color:var(--accent);text-decoration:none;">${esc(displayName)}</a></td>
      <td style="color:var(--text)">${esc(s.label)}</td>
      <td>${typeBadge}</td>
      <td style="font-size:11px;">${esc(s.purpose)}</td>
      <td style="font-size:10px;color:var(--dim)">${modified}</td>
    </tr>`;
  }).join('');

  // Build API registry rows grouped by app
  const apps = [...new Set(API_REGISTRY.map(e => e.app))];
  const apiSections = apps.map((app, i) => {
    const endpoints = API_REGISTRY.filter(e => e.app === app);
    const appColor = app === 'VectraArchForge' ? 'var(--accent)' :
                     app === 'VectraArchConduit' ? '#6a8aff' : '#e05c8a';
    const proc = processes.find(p => p.name === app);
    const statusDot = proc
      ? `<span style="display:inline-block;width:7px;height:7px;border-radius:50%;background:${proc.status==='online'?'var(--accent)':'var(--red)'};margin-right:8px;"></span>`
      : '';
    const rows = endpoints.map(e => {
      const methodColor = e.method==='GET'?'var(--accent)':e.method==='POST'?'#6a8aff':e.method==='DELETE'?'var(--red)':'var(--warn)';
      return `<tr>
        <td><span style="font-family:DM Mono,monospace;font-size:9px;letter-spacing:0.12em;color:${methodColor};border:1px solid ${methodColor};padding:1px 7px;">${e.method}</span></td>
        <td style="font-family:DM Mono,monospace;font-size:11px;color:var(--accent2)">${esc(e.path)}</td>
        <td style="font-size:11px;color:var(--text-muted)">${esc(e.desc)}</td>
      </tr>`;
    }).join('');
    return `
    <div style="margin-bottom:24px;">
      <div style="display:flex;align-items:center;gap:10px;margin-bottom:12px;padding-bottom:10px;border-bottom:1px solid var(--border);">
        ${statusDot}<span style="font-family:'Barlow Condensed',sans-serif;font-weight:700;font-size:14px;letter-spacing:0.1em;text-transform:uppercase;color:${appColor}">${app}</span>
        <span style="font-family:DM Mono,monospace;font-size:9px;color:var(--dim)">${endpoints.length} endpoints</span>
      </div>
      <table><thead><tr><th>Method</th><th>Path</th><th>Description</th></tr></thead><tbody>${rows}</tbody></table>
    </div>`;
  }).join('');

  const body = `
    <div class="page-title">Observatory</div>
    <div class="page-sub">§ Process Status · Constellation Map · API Registry</div>
    ${flash?`<div class="alert ${flash.type}">${esc(flash.msg)}</div>`:''}

    <div class="section">
      <div class="section-hdr"><span class="sh-num">01</span><span class="sh-title">PM2 · Process Status · ${processes.length} Processes</span><div class="sh-line"></div></div>
      ${processes.length===0
        ? '<div style="padding:24px;background:var(--bg2);color:var(--dim);text-align:center;letter-spacing:0.1em;font-family:DM Mono,monospace;font-size:10px;">PM2 data unavailable</div>'
        : `<table><thead><tr><th>Name</th><th>Status</th><th>PID</th><th>Uptime</th><th>Restarts</th><th>Memory</th><th>CPU</th></tr></thead><tbody>${pm2Rows}</tbody></table>`}
    </div>

    <div class="section">
      <div class="section-hdr"><span class="sh-num">02</span><span class="sh-title">Constellation · ${KNOWN_SITES.length} Sites</span><div class="sh-line"></div></div>
      <table><thead><tr><th>Path</th><th>Label</th><th>Type</th><th>Purpose</th><th>Last Modified</th></tr></thead><tbody>${siteRows}</tbody></table>
    </div>

    <div class="section">
      <div class="section-hdr"><span class="sh-num">03</span><span class="sh-title">API Registry · ${API_REGISTRY.length} Endpoints</span><div class="sh-line"></div></div>
      ${apiSections}
    </div>`;
  res.send(layout('Observatory', 'sites', body));
});

app.get(BASE + '/sites/new', isAuth, (req, res) => {
  const flash = req.session.flash; delete req.session.flash;
  res.send(siteFormPage(null, flash));
});

app.post(BASE + '/sites/new', isAuth, async (req, res) => {
  let sub = (req.body.subdomain||'').trim().toLowerCase().replace(/[^a-z0-9-]/g,'');
  if (!sub) { req.session.flash={type:'err',msg:'Subdomain required'}; return res.redirect(BASE + '/sites/new'); }
  const subdomain = sub.includes('.')?sub:`${sub}.vectraarch.live`;
  const data = parseFormToSiteData(req.body, subdomain);
  if (!data.siteTitle||!data.heroTitle) { req.session.flash={type:'err',msg:'Site Title and Hero Title are required'}; return res.redirect(BASE + '/sites/new'); }
  writeSite(subdomain, buildVAPage(data));
  await pool.query('INSERT INTO conduit_sites (subdomain,label,purpose) VALUES ($1,$2,$3) ON CONFLICT (subdomain) DO UPDATE SET label=$2,purpose=$3,updated=NOW()',
    [subdomain, data.siteTitle, req.body.purpose||'']);
  await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)', ['site_create',`subdomain:${subdomain}`,'ok']);
  res.send(deployCommandsPage(subdomain, buildNginxConfig(subdomain)));
});

app.get(BASE + '/sites/edit/:subdomain', isAuth, (req, res) => {
  const subdomain = req.params.subdomain;
  const site = KNOWN_SITES.find(s=>s.subdomain===subdomain);
  if (!site||site.type!=='static') { req.session.flash={type:'err',msg:'Site not editable here'}; return res.redirect(BASE + '/sites'); }
  const flash = req.session.flash; delete req.session.flash;
  res.send(siteFormPage(subdomain, flash));
});

app.post(BASE + '/sites/edit/:subdomain', isAuth, async (req, res) => {
  const subdomain = req.params.subdomain;
  const site = KNOWN_SITES.find(s=>s.subdomain===subdomain);
  if (!site||site.type!=='static') { req.session.flash={type:'err',msg:'Not editable'}; return res.redirect(BASE + '/sites'); }
  const data = parseFormToSiteData(req.body, subdomain);
  if (!data.siteTitle||!data.heroTitle) { req.session.flash={type:'err',msg:'Site Title and Hero Title are required'}; return res.redirect(`${BASE}/sites/edit/${subdomain}`); }
  try { const ex=readSite(subdomain); if(ex) fs.writeFileSync(siteIndexPath(subdomain)+'.bak',ex,'utf8'); } catch {}
  writeSite(subdomain, buildVAPage(data));
  await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)', ['site_edit',`subdomain:${subdomain} title:${data.siteTitle}`,'ok']);
  req.session.flash = { type:'ok', msg:`✓ ${subdomain} updated and deployed` };
  res.redirect(`${BASE}/sites/edit/${subdomain}`);
});

// ── USERS ─────────────────────────────────────────────────────────────────────
app.get(BASE + '/users', isAuth, async (req, res) => {
  const flash = req.session.flash; delete req.session.flash;
  const result = await pool.query(`
    SELECT id,name,type,role,status,logins,last_login,
           (twofa_secret IS NOT NULL) as twofa_enabled,
           CASE WHEN type='Manual' THEN COALESCE(email, '[No email set]') ELSE email END as display_email
    FROM users ORDER BY last_login DESC NULLS LAST
  `);
  const users = result.rows;

  const rows = users.map(u=>`
    <tr>
      <td><div style="color:var(--text);font-size:12px;">${esc(u.name)}</div><div style="color:var(--dim);font-size:10px;">${esc(u.display_email)}</div></td>
      <td><span class="badge ${u.type==='Google'?'ok':'info'}">${esc(u.type)}</span></td>
      <td><span class="badge ${u.role==='admin'?'warn':'info'}">${esc(u.role)}</span></td>
      <td><span class="badge ${u.status==='enabled'?'ok':'err'}">${esc(u.status)}</span></td>
      <td style="font-size:10px;color:var(--dim)">${u.logins||0}</td>
      <td style="font-size:10px;color:var(--dim)">${u.last_login||'—'}</td>
      <td><span class="badge ${u.twofa_enabled?'ok':'info'}">${u.twofa_enabled?'On':'Off'}</span></td>
      <td style="white-space:nowrap;">
        <div style="display:flex;gap:6px;flex-wrap:wrap;">
          <button class="btn" onclick="toggleEdit('${esc(u.id)}')" type="button">Edit</button>
          ${u.twofa_enabled?`<form method="POST" action="${BASE}/users/reset-2fa/${encodeURIComponent(u.id)}" style="display:inline;"><button class="btn" type="submit" onclick="return confirm('Reset 2FA?')">2FA ✕</button></form>`:''}
          <form method="POST" action="${BASE}/users/edit/${encodeURIComponent(u.id)}" style="display:inline;">
            <input type="hidden" name="name" value="${esc(u.name)}"/>
            <input type="hidden" name="role" value="${esc(u.role)}"/>
            <input type="hidden" name="status" value="${u.status==='enabled'?'disabled':'enabled'}"/>
            <button class="btn ${u.status==='enabled'?'danger':''}" type="submit">${u.status==='enabled'?'Disable':'Enable'}</button>
          </form>
          <form method="POST" action="${BASE}/users/delete/${encodeURIComponent(u.id)}" style="display:inline;">
            <button class="btn danger" type="submit" onclick="return confirm('Delete ${esc(u.name)}?')">Delete</button>
          </form>
        </div>
        <div id="edit-${esc(u.id)}" style="display:none;margin-top:12px;background:var(--bg3);border:1px solid var(--border2);padding:16px;">
          <form method="POST" action="${BASE}/users/edit/${encodeURIComponent(u.id)}">
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:10px;">
              <div><div class="form-label" style="margin-bottom:4px;">Name</div><input class="form-input" name="name" value="${esc(u.name)}" required/></div>
              <div><div class="form-label" style="margin-bottom:4px;">Role</div>
                <select class="form-select" name="role"><option value="user" ${u.role==='user'?'selected':''}>User</option><option value="admin" ${u.role==='admin'?'selected':''}>Admin</option></select>
              </div>
              <div><div class="form-label" style="margin-bottom:4px;">Status</div>
                <select class="form-select" name="status"><option value="enabled" ${u.status==='enabled'?'selected':''}>Enabled</option><option value="disabled" ${u.status==='disabled'?'selected':''}>Disabled</option></select>
              </div>
              ${u.type==='Manual'?`<div><div class="form-label" style="margin-bottom:4px;">Email (optional)</div><input class="form-input" name="email" type="email" placeholder="email address" value=""/></div><div><div class="form-label" style="margin-bottom:4px;">New Password</div><input class="form-input" name="password" type="password" placeholder="leave blank to keep"/></div>`:'<div></div>'}
            </div>
            <div style="display:flex;gap:8px;">
              <button class="btn primary" type="submit">Save</button>
              <button class="btn" type="button" onclick="toggleEdit('${esc(u.id)}')">Cancel</button>
            </div>
          </form>
        </div>
      </td>
    </tr>`).join('');

  const body = `
    <div class="page-title">Users</div>
    <div class="page-sub">§ User Management · bookforge database</div>
    ${flash?`<div class="alert ${flash.type}">${esc(flash.msg)}</div>`:''}
    <div class="stat-row">
      <div class="stat-cell"><div class="stat-num">${users.length}</div><div class="stat-label">Total Users</div></div>
      <div class="stat-cell"><div class="stat-num">${users.filter(u=>u.role==='admin').length}</div><div class="stat-label">Admins</div></div>
      <div class="stat-cell"><div class="stat-num">${users.filter(u=>u.type==='Google').length}</div><div class="stat-label">Google OAuth</div></div>
      <div class="stat-cell"><div class="stat-num">${users.filter(u=>u.twofa_enabled).length}</div><div class="stat-label">2FA Enabled</div></div>
    </div>
    <div class="section">
      <div class="section-hdr"><span class="sh-num">01</span><span class="sh-title">Add New User</span><div class="sh-line"></div></div>
      <div class="form-wrap" style="padding:24px 32px;">
        <form method="POST" action="${BASE}/users/add">
          <div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr auto;gap:12px;align-items:end;">
            <div class="form-group" style="margin:0;"><label class="form-label">Name <span class="req">*</span></label><input class="form-input" name="name" placeholder="username" required/></div>
            <div class="form-group" style="margin:0;"><label class="form-label">Email</label><input class="form-input" name="email" type="email" placeholder="email address (optional)"/></div>
            <div class="form-group" style="margin:0;"><label class="form-label">Password <span class="req">*</span></label><input class="form-input" name="password" type="password" placeholder="password" required/></div>
            <div class="form-group" style="margin:0;"><label class="form-label">Type</label><select class="form-select" name="type"><option value="Manual">Manual</option><option value="Google">Google</option></select></div>
            <div class="form-group" style="margin:0;"><label class="form-label">Role</label><select class="form-select" name="role"><option value="user">User</option><option value="admin">Admin</option></select></div>
            <button class="btn primary" type="submit" style="padding:10px 20px;">Add ↗</button>
          </div>
        </form>
      </div>
    </div>
    <div class="section">
      <div class="section-hdr"><span class="sh-num">02</span><span class="sh-title">All Users · ${users.length} Accounts</span><div class="sh-line"></div></div>
      <table><thead><tr><th>Name</th><th>Type</th><th>Role</th><th>Status</th><th>Logins</th><th>Last Login</th><th>2FA</th><th>Actions</th></tr></thead><tbody>${rows}</tbody></table>
    </div>
    <script>function toggleEdit(id){const el=document.getElementById('edit-'+id);el.style.display=el.style.display==='none'?'block':'none';}</script>`;

  res.send(layout('Users', 'users', body));
});

app.post(BASE + '/users/add', isAuth, async (req, res) => {
  const { name, email, password, type, role } = req.body;
  if (!name||!password) { req.session.flash={type:'err',msg:'Name and Password required'}; return res.redirect(BASE + '/users'); }
  const t = type==='Google'?'Google':'Manual';
  const newId = (t==='Google'?'g_':'m_') + Date.now();
  await pool.query('INSERT INTO users (id,name,email,password,type,role,status,logins) VALUES ($1,$2,$3,$4,$5,$6,$7,0)',
    [newId, name, email||null, password, t, role==='admin'?'admin':'user', 'enabled']);
  await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)', ['user_add',`name:${name}`,'ok']);
  req.session.flash = { type:'ok', msg:`✓ User "${name}" created` };
  res.redirect(BASE + '/users');
});

app.post(BASE + '/users/edit/:id', isAuth, async (req, res) => {
  const uid = req.params.id;
  const { name, role, status, password } = req.body;
  if (!name) { req.session.flash={type:'err',msg:'Name required'}; return res.redirect(BASE + '/users'); }
  await pool.query('UPDATE users SET name=$1,role=$2,status=$3 WHERE id=$4', [name, role==='admin'?'admin':'user', status==='disabled'?'disabled':'enabled', uid]);
  if (password&&password.trim()) await pool.query("UPDATE users SET password=$1 WHERE id=$2 AND type='Manual'", [password.trim(), uid]);
  await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)', ['user_edit',`id:${uid} name:${name}`,'ok']);
  req.session.flash = { type:'ok', msg:`✓ User "${name}" updated` };
  res.redirect(BASE + '/users');
});

app.post(BASE + '/users/reset-2fa/:id', isAuth, async (req, res) => {
  await pool.query('UPDATE users SET twofa_secret=NULL WHERE id=$1', [req.params.id]);
  await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)', ['user_reset_2fa',`id:${req.params.id}`,'ok']);
  req.session.flash = { type:'ok', msg:'✓ 2FA reset' };
  res.redirect(BASE + '/users');
});

app.post(BASE + '/users/delete/:id', isAuth, async (req, res) => {
  const uid = req.params.id;
  if (uid === req.session.conduitUser.id) { req.session.flash={type:'err',msg:'Cannot delete your own account'}; return res.redirect(BASE + '/users'); }
  const u = await pool.query('SELECT name FROM users WHERE id=$1', [uid]);
  const name = u.rows[0]?.name||uid;
  await pool.query('DELETE FROM users WHERE id=$1', [uid]);
  await pool.query('INSERT INTO conduit_log (event,payload,status) VALUES ($1,$2,$3)', ['user_delete',`id:${uid} name:${name}`,'ok']);
  req.session.flash = { type:'ok', msg:`✓ User "${name}" deleted` };
  res.redirect(BASE + '/users');
});

// ── PAGE BUILDERS ─────────────────────────────────────────────────────────────
function loginPage(err) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>Conduit · Access</title>${FONTS}<style>${CSS}</style></head><body>
<div class="grid-bg"></div>
<div class="accent-lines" aria-hidden="true">
  <svg viewBox="0 0 600 900" fill="none" preserveAspectRatio="xMaxYMid slice">
    <line x1="580" y1="0" x2="20" y2="900" stroke="rgba(0,255,65,0.07)" stroke-width="1"/>
    <line x1="540" y1="0" x2="0" y2="760" stroke="rgba(0,255,65,0.05)" stroke-width="0.5"/>
    <circle cx="540" cy="180" r="90" stroke="rgba(0,255,65,0.025)" stroke-width="0.5" fill="none"/>
  </svg>
</div>
<div class="login-wrap">
  <div class="login-card">
    <div class="login-eyebrow">§ Vectra Arch · Conduit Hub</div>
    <div class="login-title">Access</div>
    <div class="login-sub">Automation &amp; Social Hub · Authorised Entry Only</div>
    <form method="POST" action="${BASE}/login">
      <div class="field"><label>Username</label><input name="cid" type="text" placeholder="admin" autocomplete="username" required autofocus/></div>
      <div class="field"><label>Key</label><input name="ak" type="password" placeholder="········" autocomplete="current-password" required/></div>
      <button class="btn primary" type="submit" style="width:100%;justify-content:center;margin-top:8px;">Authenticate ↗</button>
      ${err?`<div class="login-err">⚠ ${esc(err)}</div>`:''}
    </form>
    <div style="margin-top:24px;text-align:center;">
      <a href="${FOUNDATION_URL}" style="font-family:DM Mono,monospace;font-size:9px;letter-spacing:0.14em;color:var(--dim);text-decoration:none;">← Back to Foundation</a>
    </div>
  </div>
</div></body></html>`;
}

function twoFAVerifyPage(err) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>2FA · Conduit</title>${FONTS}<style>${CSS}</style></head><body>
<div class="grid-bg"></div>
<div class="login-wrap">
  <div class="login-card">
    <div class="login-eyebrow">§ Vectra Arch · Conduit · 2FA</div>
    <div class="login-title">Verify</div>
    <div class="login-sub">Enter the 6-digit code from your authenticator app</div>
    <form method="POST" action="${BASE}/auth/2fa">
      <div class="field"><label>Authentication Code</label>
        <input name="token" type="text" placeholder="000000" maxlength="6" autocomplete="one-time-code" required autofocus style="font-size:24px;letter-spacing:0.3em;text-align:center;"/>
      </div>
      <button class="btn primary" type="submit" style="width:100%;justify-content:center;margin-top:8px;">Verify ↗</button>
      ${err?`<div class="login-err">⚠ ${esc(err)}</div>`:''}
    </form>
  </div>
</div></body></html>`;
}

async function twoFASetupPage(qr, secret, err) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>Setup 2FA · Conduit</title>${FONTS}<style>${CSS}</style></head><body>
<div class="grid-bg"></div>
<div class="login-wrap">
  <div class="login-card" style="max-width:440px;">
    <div class="login-eyebrow">§ Vectra Arch · Conduit · Setup 2FA</div>
    <div class="login-title">Enable 2FA</div>
    <div class="login-sub">Scan the QR code with your authenticator app</div>
    ${qr?`<div style="text-align:center;margin-bottom:20px;background:white;padding:16px;"><img src="${qr}" alt="QR Code" style="width:180px;height:180px;display:block;margin:0 auto;"/></div>`:''}
    <div style="font-family:DM Mono,monospace;font-size:9px;color:var(--dim);letter-spacing:0.12em;margin-bottom:24px;text-align:center;">
      Manual key: <span style="color:var(--accent);letter-spacing:0.2em;">${esc(secret||'')}</span>
    </div>
    <form method="POST" action="${BASE}/auth/2fa/setup">
      <div class="field"><label>Confirm Code</label>
        <input name="token" type="text" placeholder="000000" maxlength="6" autocomplete="one-time-code" required autofocus style="font-size:20px;letter-spacing:0.3em;text-align:center;"/>
      </div>
      <button class="btn primary" type="submit" style="width:100%;justify-content:center;margin-top:8px;">Activate 2FA ↗</button>
      ${err?`<div class="login-err">⚠ ${esc(err)}</div>`:''}
    </form>
    <div style="margin-top:16px;text-align:center;"><a href="${BASE}/" style="font-family:DM Mono,monospace;font-size:9px;letter-spacing:0.14em;color:var(--dim);text-decoration:none;">← Cancel</a></div>
  </div>
</div></body></html>`;
}

function siteFormPage(subdomain, flash) {
  const isEdit = !!subdomain;
  const title  = isEdit ? `Edit · ${subdomain}` : 'New Site';
  const action = isEdit ? `${BASE}/sites/edit/${encodeURIComponent(subdomain)}` : `${BASE}/sites/new`;

  const coordFields = [1,2,3,4,5,6].map(i=>`
    <div class="form-group"><label class="form-label">Coord ${i} Key</label><input class="form-input" name="coord${i}key"/></div>
    <div class="form-group"><label class="form-label">Coord ${i} Value</label><input class="form-input" name="coord${i}val"/></div>`).join('');

  const sectionFields = [1,2,3,4].map(si=>`
    <div class="narrative-block">
      <div class="narrative-block-title">Section ${si}</div>
      <div class="form-grid">
        <div class="form-group"><label class="form-label">Number</label><input class="form-input" name="sec${si}num" placeholder="0${si}"/></div>
        <div class="form-group"><label class="form-label">Title</label><input class="form-input" name="sec${si}title"/></div>
      </div>
      ${[1,2,3].map(ni=>`
      <div class="narrative-block" style="margin-top:12px;background:var(--bg2);">
        <div class="narrative-block-title">Narrative ${ni}</div>
        <div class="form-grid">
          <div class="form-group"><label class="form-label">Tag</label><input class="form-input" name="sec${si}n${ni}tag"/></div>
          <div class="form-group"><label class="form-label">Year</label><input class="form-input" name="sec${si}n${ni}year"/></div>
          <div class="form-group full"><label class="form-label">Heading</label><input class="form-input" name="sec${si}n${ni}heading"/></div>
          <div class="form-group full"><label class="form-label">Body 1</label><textarea class="form-textarea" name="sec${si}n${ni}body1"></textarea></div>
          <div class="form-group full"><label class="form-label">Body 2 (optional)</label><textarea class="form-textarea" name="sec${si}n${ni}body2"></textarea></div>
        </div>
      </div>`).join('')}
    </div>`).join('');

  const footerFields = [1,2,3].map(i=>`
    <div class="form-grid">
      <div class="form-group"><label class="form-label">Link ${i} Label</label><input class="form-input" name="fl${i}label"/></div>
      <div class="form-group"><label class="form-label">Link ${i} URL</label><input class="form-input" name="fl${i}url"/></div>
    </div>`).join('');

  const body = `
    <div class="page-title">${isEdit?'Edit Site':'New Site'}</div>
    <div class="page-sub">§ ${isEdit?subdomain:'Create a new VectraArch subdomain'}</div>
    ${flash?`<div class="alert ${flash.type}">${esc(flash.msg)}</div>`:''}
    <form method="POST" action="${action}">
      <div class="form-wrap">
        ${!isEdit?`
        <div class="form-section">
          <div class="form-section-title">§ 00 · Subdomain</div>
          <div class="form-grid">
            <div class="form-group"><label class="form-label">Subdomain <span class="req">*</span></label><input class="form-input" name="subdomain" placeholder="e.g. newsite" required/><div class="form-hint">Becomes newsite.vectraarch.live</div></div>
            <div class="form-group"><label class="form-label">Purpose</label><input class="form-input" name="purpose" placeholder="What is this site for?"/></div>
          </div>
        </div>`:''}
        <div class="form-section">
          <div class="form-section-title">§ 01 · Identity</div>
          <div class="form-grid">
            <div class="form-group"><label class="form-label">Site Title <span class="req">*</span></label><input class="form-input" name="siteTitle" required/></div>
            <div class="form-group"><label class="form-label">Studio Number</label><input class="form-input" name="studioNum" placeholder="e.g. 01 / 08"/></div>
            <div class="form-group full"><label class="form-label">Meta Description</label><input class="form-input" name="metaDesc"/></div>
          </div>
        </div>
        <div class="form-section">
          <div class="form-section-title">§ 02 · Hero</div>
          <div class="form-grid">
            <div class="form-group full"><label class="form-label">Eyebrow</label><input class="form-input" name="eyebrow"/></div>
            <div class="form-group"><label class="form-label">Hero Title <span class="req">*</span></label><input class="form-input" name="heroTitle" required/></div>
            <div class="form-group"><label class="form-label">Hero Ghost (outline)</label><input class="form-input" name="heroTitleGhost"/></div>
            <div class="form-group full"><label class="form-label">Tagline</label><textarea class="form-textarea" name="heroTagline"></textarea><div class="form-hint">Each line becomes a br</div></div>
          </div>
        </div>
        <div class="form-section">
          <div class="form-section-title">§ 03 · Coordinates</div>
          <div class="form-grid">${coordFields}</div>
        </div>
        <div class="form-section">
          <div class="form-section-title">§ 04 · Sections</div>
          ${sectionFields}
        </div>
        <div class="form-section">
          <div class="form-section-title">§ 05 · Terminal (optional)</div>
          <div class="form-grid">
            <div class="form-group"><label class="form-label">Prompt</label><input class="form-input" name="terminalPrompt" placeholder="schalk@vectraarch:~/fabric"/></div>
            <div class="form-group"><label class="form-label">Command</label><input class="form-input" name="terminalCmd" placeholder="ls -la"/></div>
          </div>
        </div>
        <div class="form-section">
          <div class="form-section-title">§ 06 · Footer</div>
          <div class="form-grid"><div class="form-group"><label class="form-label">Footer Logo</label><input class="form-input" name="footerLogo"/></div></div>
          ${footerFields}
        </div>
        <div class="form-actions">
          <button class="btn primary" type="submit">${isEdit?'Save & Deploy ↗':'Create Site ↗'}</button>
          <a href="${BASE}/sites" class="btn">← Back</a>
          ${isEdit?`<a href="https://vectraarch.live/${esc(subdomain)}/" target="_blank" class="btn">View Live ↗</a>`:''}
        </div>
      </div>
    </form>`;

  return layout(title, 'sites', body);
}

function deployCommandsPage(subdomain, nginxConf) {
  const commands = `# The HTML has been written to:
# /var/www/vectraarch.live/${subdomain}/index.html
#
# Add this location block to /etc/nginx/sites-enabled/vectraarch.live
# inside the main server {} block, then reload nginx:
#
#   location /${subdomain}/ {
#       try_files $uri $uri/ /${subdomain}/index.html;
#   }
#
# nginx -t && systemctl reload nginx
#
# No SSL cert needed — vectraarch.live cert already covers the path.`;

  const body = `
    <div class="page-title">Deploy</div>
    <div class="page-sub">§ ${esc(subdomain)} · Run these commands on your server</div>
    <div class="alert ok">✓ HTML written to /var/www/${esc(subdomain)}/index.html — run commands below to go live.</div>
    <div class="section">
      <div class="section-hdr"><span class="sh-num">01</span><span class="sh-title">Server Commands</span><div class="sh-line"></div></div>
      <div class="code-block">${esc(commands)}</div>
    </div>
    <div style="display:flex;gap:12px;margin-top:20px;">
      <a href="${BASE}/sites/edit/${encodeURIComponent(subdomain)}" class="btn primary">Edit Site ↗</a>
      <a href="${BASE}/sites" class="btn">← All Sites</a>
    </div>`;

  return layout(`Deploy · ${subdomain}`, 'sites', body);
}

// ── START ─────────────────────────────────────────────────────────────────────
setupDB().then(() => {
  app.listen(PORT, HOST, () => {
    console.log(`[conduit] Listening on ${HOST}:${PORT}`);
    console.log(`[conduit] Routes: /, /sites, /users, /login, /auth/2fa`);
  });
}).catch(e => { console.error('[conduit] DB setup failed:', e); process.exit(1); });
